import Foundation
import IsolatorCore

// Image delivery is opt-in, and limited to PNGs created in this MCP session.
final class ImageDelivery: @unchecked Sendable {
  private let lock = NSLock()
  private var paths: Set<String> = []
  func remember(_ reply: J) {
    lock.lock()
    defer { lock.unlock() }
    let r = reply["result"]
    if r["path"].s.hasSuffix(".png") { paths.insert(r["path"].s) }
    for tile in r["tiles"].a where tile["path"].s.hasSuffix(".png") { paths.insert(tile["path"].s) }
    while paths.count > 128 { paths.remove(paths.first!) }
  }
  func read(_ p: J) throws -> J {
    guard p["vision"].b else {
      throw AutomationError(
        "vision_required", "Confirm the model and tool chain support image input")
    }
    lock.lock()
    let known = paths.contains(p["path"].s)
    lock.unlock()
    guard known else {
      throw AutomationError(
        "unknown_artifact", "Only screenshots generated by this MCP session can be delivered")
    }
    let url = URL(fileURLWithPath: p["path"].s)
    let size =
      (try FileManager.default.attributesOfItem(atPath: url.path)[.size] as? NSNumber)?.intValue
      ?? 0
    guard size > 0 && size <= 2 * 1024 * 1024 else {
      throw AutomationError("image_too_large", "PNG must be at most 2 MiB")
    }
    let data = try Data(contentsOf: url)
    guard data.count <= 2 * 1024 * 1024, Array(data.prefix(8)) == [137, 80, 78, 71, 13, 10, 26, 10]
    else { throw AutomationError("invalid_image", "Artifact is not a bounded PNG") }
    return [
      "content": [
        ["type": "image", "mimeType": "image/png", "data": .str(data.base64EncodedString())]
      ], "isError": false,
    ]
  }
}
