// Run with TEST_HARNESS (JSON argv), CHROME_BINARY, and optionally TEST_CLI (JSON argv).
// Only new temporary browser data is used. No production configuration is opened.
import {spawn} from 'node:child_process';
import {createServer} from 'node:http';
import {mkdtemp,readFile,writeFile,rm,stat} from 'node:fs/promises';
import {tmpdir} from 'node:os';
import {join} from 'node:path';
import {createInterface} from 'node:readline';
import assert from 'node:assert/strict';
import {inflateSync} from 'node:zlib';
const temporary=await mkdtemp(join(tmpdir(),'isolator-automation-test-'));
let chrome,harness;const servers=[];let assertions=0;const testPipe='ChromeIsolator.Automation.Test.'+crypto.randomUUID();
const check=(v,message)=>{assert.ok(v,message);assertions++};
const greenPixels=async path=>{
 const png=await readFile(path);let width,height,type,parts=[];for(let i=8;i<png.length;){const n=png.readUInt32BE(i),kind=png.toString('ascii',i+4,i+8),data=png.subarray(i+8,i+8+n);if(kind==='IHDR'){width=data.readUInt32BE(0);height=data.readUInt32BE(4);type=data[9];}if(kind==='IDAT')parts.push(data);i+=n+12;}
 const channels=type===6?4:3;assert.ok(type===2||type===6);const raw=inflateSync(Buffer.concat(parts)),row=width*channels;let previous=Buffer.alloc(row),offset=0,green=0;
 for(let y=0;y<height;y++){const filter=raw[offset++],line=Buffer.from(raw.subarray(offset,offset+row));offset+=row;for(let x=0;x<row;x++){const a=x>=channels?line[x-channels]:0,b=previous[x],c=x>=channels?previous[x-channels]:0;const p=a+b-c,pa=Math.abs(p-a),pb=Math.abs(p-b),pc=Math.abs(p-c);const predictor=filter===1?a:filter===2?b:filter===3?Math.floor((a+b)/2):filter===4?(pa<=pb&&pa<=pc?a:pb<=pc?b:c):0;line[x]=(line[x]+predictor)&255;}for(let x=0;x<row;x+=channels)if(line[x]<70&&line[x+1]>130&&line[x+2]<70)green++;previous=line;}return green;
};
try {
 const fixture=await readFile(new URL('../fixtures/page.html',import.meta.url),'utf8');
 const handler=(req,res)=>{res.setHeader('Content-Type','text/html');if(req.url==='/frame'||req.url==='/nested-frame')res.end('<html><body><button id="framebutton" style="background:rgb(30,180,30);width:160px;height:60px" onclick="document.querySelector(\'#result\').textContent=\'Frame done\'">Frame action</button><div id="result">Waiting</div>'+(req.url==='/frame'?'<iframe src="/nested-frame" style="width:250px;height:100px"></iframe>':'')+'</body></html>');else if(req.url==='/data'){res.setHeader('Set-Cookie','private=secret');res.end('{}')}else res.end(fixture.replace('CROSS_ORIGIN',crossOrigin));};
 const listen=async()=>{const s=createServer(handler);await new Promise(resolve=>s.listen(0,'127.0.0.1',resolve));servers.push(s);return s.address().port;};
 const a=await listen(),b=await listen();const crossOrigin=`http://localhost:${b}`;const url=`http://127.0.0.1:${a}`;
 chrome=spawn(process.env.CHROME_BINARY??'/Applications/Google Chrome.app/Contents/MacOS/Google Chrome',['--headless=new','--remote-debugging-port=0',`--user-data-dir=${join(temporary,'browser')}`,'--no-first-run','--no-default-browser-check','--site-per-process','about:blank'],{stdio:'ignore'});
 let port;for(let i=0;i<150;i++){try{port=Number((await readFile(join(temporary,'browser','DevToolsActivePort'),'utf8')).split('\n')[0]);break;}catch{await new Promise(r=>setTimeout(r,100));}}check(port>0,'temporary browser debugging endpoint');
 const argv=JSON.parse(process.env.TEST_HARNESS);harness=spawn(argv[0],argv.slice(1),{env:{...process.env,TEST_CDP_PORT:String(port),TEST_PROFILE_COUNT:'67',ISOLATOR_PIPE:testPipe,ISOLATOR_SOCKET:join(temporary,'automation.sock')},stdio:['pipe','pipe','pipe']});harness.stderr.on('data',d=>process.stderr.write(d));const lines=createInterface({input:harness.stdout});const pending=[];lines.on('line',line=>{const p=pending.shift();if(p){try{p.resolve(JSON.parse(line))}catch(e){p.reject(e)}}});harness.on('exit',code=>{for(const p of pending.splice(0))p.reject(Error('Harness exited '+code));});
 const raw=(operation,params={},id=crypto.randomUUID())=>new Promise((resolve,reject)=>{const timer=setTimeout(()=>reject(Error('Harness timeout '+operation)),45000);pending.push({resolve:v=>{clearTimeout(timer);resolve(v)},reject});harness.stdin.write(JSON.stringify({id,operation,params})+'\n')});
 const call=async(op,p={})=>{const r=await raw(op,{profile:'test',...p});check(r.ok,op+': '+JSON.stringify(r.error));return r.result;};
 const caps=await call('system.capabilities');check(caps.operations.length>=32,'complete operation registry');
 const environments=await call('profile.list');check(environments.profiles.length>0&&environments.nextOffset>0&&JSON.stringify(environments).length<=6000,'large environment list keeps bounded page');const moreEnvironments=await call('profile.list',{offset:environments.nextOffset});check(moreEnvironments.profiles[0].profile==='dummy'+environments.nextOffset,'bounded profile nextOffset is usable');
 check(!(await raw('unknown',{})).ok,'unknown operation');check(!(await raw('page.open',{profile:'test',url:'file:///tmp/private'})).ok,'reject non-web URL');
 const opened=await call('page.open',{url});const tab=opened.tab;check(tab,'explicit opened tab');await new Promise(r=>setTimeout(r,600));
 const read=await call('page.snapshot',{tab,maxChars:14000});check(read.nodes.some(n=>n.name==='Load async'),'semantic snapshot');check(read.frames.length===5,'all iframe domains: '+JSON.stringify({frames:read.frames,gaps:read.gaps}));check(read.coverage.canvas.includes('screenshot'),'canvas coverage declared');const snapshot=read.snapshot;
 const detail=await call('page.search',{tab,snapshot,query:'hidden',view:'full',includeHidden:true,maxChars:14000});check(detail.nodes.some(n=>n.attributes?.id==='hidden'),'hidden DOM discoverable');
 const pageOne=await call('page.expand',{tab,snapshot,limit:1});check(pageOne.nodes.length===1&&pageOne.nextOffset===1,'bounded snapshot pagination');const limited=await call('page.snapshot',{tab,maxNodes:5});check(!limited.captureComplete&&limited.gaps.length>0,'capture limit declared');
 const load=read.nodes.find(n=>n.name==='Load async');const action=await call('page.click',{tab,snapshot,ref:load.ref,observe:true,until:{selector:'#status',state:'text',text:'Loaded'},timeout:8,maxChars:14000});check(action.observation.conditionMet,'dynamic completion condition: '+JSON.stringify(action.observation));check(action.observation.diff.totalChanges>0,'before/after diff');
 const diag=await call('diagnostics.get',{tab,maxChars:14000});check(diag.events.some(e=>e.method==='Network.responseReceived'),'observed network');check(!JSON.stringify(diag).includes('private=secret'),'headers excluded');
 await call('page.fill',{tab,selector:'#name',value:'123 中文'});const input=await call('page.inspect',{tab,selector:'#name',live:true,fields:'attributes',maxChars:100000});check(input.outerHTML.includes('id="name"'),'live DOM details');check(!(await raw('page.fill',{profile:'test',tab,selector:'#name',value:123})).ok,'wrong parameter type rejected before input');check((await call('page.evaluate',{tab,expression:'document.querySelector("#name").value'})).value==='123 中文','invalid fill leaves input untouched');check((await raw('page.wait',{profile:'test',tab,selector:'#status',state:'typo'})).error.code==='invalid_state','invalid completion state rejected');
 const rejectedReadonly=await raw('page.fill',{profile:'test',tab,selector:'#readonly',value:'REPLACE'});check(!rejectedReadonly.ok&&rejectedReadonly.error.code==='element_readonly','readonly fill rejects before mutation');check((await call('page.evaluate',{tab,expression:'document.querySelector("#readonly").value'})).value==='KEEP','readonly value preserved');
 check(!(await raw('page.fill',{profile:'test',tab,selector:'#date',value:'2026-11-01'})).ok,'non-text input rejects fill');check((await call('page.evaluate',{tab,expression:'document.querySelector("#date").value'})).value==='2026-10-02','unsupported fill preserves value');
 check(!(await raw('page.fill',{profile:'test',tab,selector:'#number',value:'invalid'})).ok,'numeric input rejects incompatible value');check((await call('page.evaluate',{tab,expression:'document.querySelector("#number").value'})).value==='123','invalid numeric fill preserves value');
 check((await call('page.wait',{tab,name:'Only named control',state:'visible',timeout:1})).conditionMet,'name-only wait supported');
 const nameObserved=await call('page.click',{tab,selector:'#reveal',observe:true,until:{name:'Later named control',state:'visible'},timeout:8});check(nameObserved.observation.conditionMet,'name-only action completion supported: '+JSON.stringify(nameObserved));
 check(!(await call('page.wait',{tab,selector:'#ariaDisabled',state:'enabled',timeout:1})).conditionMet,'ARIA disabled wait agrees with actions');check((await raw('page.click',{profile:'test',tab,selector:'#ariaDisabled'})).error.code==='element_disabled','ARIA disabled action rejected');
 check(!(await raw('page.fill',{profile:'test',tab,selector:'#fieldsetInput',value:'REPLACE'})).ok,'fieldset disabled fill rejects');check((await call('page.evaluate',{tab,expression:'document.querySelector("#fieldsetInput").value'})).value==='KEEP','fieldset disabled value preserved');
 const disabledSnapshot=await call('page.snapshot',{tab,maxChars:14000});check(disabledSnapshot.nodes.find(n=>n.name==='Unavailable')?.disabled===true,'snapshot and wait disabled states agree');
 await call('page.evaluate',{tab,expression:'document.querySelector("#ariaDisabled").setAttribute("aria-disabled","false")'});check((await call('page.wait',{tab,selector:'#ariaDisabled',state:'enabled',timeout:1})).conditionMet,'enabled condition reacts to state change');
 await call('page.evaluate',{tab,expression:'document.body.style.minWidth="2000px";scrollTo(0,0)'});const horizontal=await call('page.scroll',{tab,x:60,y:0});check(horizontal.value.x===60&&horizontal.value.y===0,'explicit zero vertical scroll preserved');const defaultScroll=await call('page.scroll',{tab,x:0});check(defaultScroll.value.y===600,'omitted vertical scroll retains default');await call('page.evaluate',{tab,expression:'document.body.style.minWidth="";scrollTo(0,0)'});
 await call('page.check',{tab,selector:'#check',checked:true});const already=await call('page.check',{tab,selector:'#check',checked:true});check(already.alreadySatisfied,'checkbox idempotence');await call('page.key',{tab,selector:'#name',key:'ArrowLeft'});check((await call('page.evaluate',{tab,expression:'document.activeElement.id'})).value==='name','key focuses explicit target');
 await call('page.select',{tab,selector:'#choice',value:'b'});const value=await call('page.evaluate',{tab,expression:'document.querySelector("#choice").value'});check(value.value==='b','selection applied');
 check(!(await raw('page.click',{profile:'test',tab,selector:'.duplicate'})).ok,'ambiguous selector never picks first');
 await call('page.click',{tab,selector:'#shadowbutton'});const shadow=await call('page.wait',{tab,selector:'#shadowstatus',state:'text',text:'Shadow done',timeout:2});check(shadow.conditionMet,'shadow actions and conditions');
 const frame=read.frames.find(f=>f.url===url+'/frame').id;await call('page.click',{tab,frame,selector:'#framebutton'});const framed=await call('page.wait',{tab,frame,selector:'#result',state:'text',text:'Frame done',timeout:2});check(framed.conditionMet,'iframe input coordinates');
 const cross=read.frames.find(f=>f.url===crossOrigin+'/frame').id;await call('page.click',{tab,frame:cross,selector:'#framebutton'});check((await call('page.wait',{tab,frame:cross,selector:'#result',state:'text',text:'Frame done',timeout:2})).conditionMet,'cross-origin frame action');
 const cropped=await call('page.screenshot',{tab,frame:cross,selector:'#framebutton',output:join(temporary,'frame.png')});check(await greenPixels(cropped.path)>100,'cross-origin element screenshot maps root coordinates');
 const leaf=read.frames.find(f=>f.url===crossOrigin+'/nested-frame').id;await call('page.click',{tab,frame:leaf,selector:'#framebutton'});const leafShot=await call('page.screenshot',{tab,frame:leaf,selector:'#framebutton',output:join(temporary,'leaf.png')});check(await greenPixels(leafShot.path)>100,'nested cross-origin element crop');
 const upload=join(temporary,'upload.txt');await writeFile(upload,'fixture');await call('page.upload',{tab,selector:'#file',files:[upload]});check((await call('page.evaluate',{tab,expression:'document.querySelector("#file").files.length'})).value===1,'local file upload');
 const wait=await call('page.wait',{tab,selector:'#missing',timeout:1});check(wait.reason==='timeout'&&!wait.conditionMet,'timeout not success');
 const watch=await call('watch.start',{tab,selector:'#missing',timeout:10});check((await call('watch.cancel',{watch:watch.watch})).state==='cancelled','watch cancellation');
 const history=[];for(let i=0;i<20;i++){const ended=await call('page.wait',{tab,name:'Only named control',state:'visible',timeout:1,maxChars:14000});history.push(ended.watch);check(ended.historyCompacted&&ended.conditionMet&&ended.diff.afterSnapshot,'terminal watch keeps completion and snapshot IDs');}
 check((await raw('watch.get',{profile:'test',watch:history[0]})).error.code==='watch_expired','completed history evicts oldest by capacity');const recentWatch=await call('watch.get',{watch:history.at(-1),maxChars:14000});check(recentWatch.historyCompacted&&recentWatch.conditionMet,'recent compacted history remains usable');const cancelEnded=await call('watch.cancel',{watch:history.at(-1)});check(cancelEnded.state==='completed'&&cancelEnded.conditionMet,'cancel does not rewrite completed result');
 const heavy=await call('watch.start',{tab,selector:'#never',timeout:10});await call('page.evaluate',{tab,expression:'console.log("x".repeat(400000))'});await new Promise(r=>setTimeout(r,700));const compacted=await call('watch.cancel',{watch:heavy.watch,output:join(temporary,'watch.json')});const savedWatch=JSON.parse(await readFile(compacted.path,'utf8'));check(savedWatch.historyCompacted&&savedWatch.historyTruncated&&savedWatch.droppedEvents>0,'large ended watch explicitly truncates history');check((await stat(compacted.path)).size<=262144,'ended watch result byte budget');
 const byteHistory=[];for(let i=0;i<13;i++){const item=await call('watch.start',{tab,selector:'#never',timeout:10});await call('page.evaluate',{tab,expression:'console.log("b".repeat(180000))'});await new Promise(r=>setTimeout(r,700));const ended=await call('watch.cancel',{watch:item.watch,output:join(temporary,`budget-${i}.json`)});const saved=JSON.parse(await readFile(ended.path,'utf8'));check(saved.events.some(e=>e.method==='Runtime.consoleAPICalled'),'history retains bounded event details');byteHistory.push(item.watch);}
 check((await raw('watch.get',{profile:'test',watch:byteHistory[0]})).error.code==='watch_expired','history total byte budget evicts before count limit');check((await call('watch.get',{watch:byteHistory.at(-1)})).historyCompacted,'byte budget preserves newest result');
 const exportPath=join(temporary,'capture.json');await call('page.capture',{tab,output:exportPath,styles:['display']});const capture=JSON.parse(await readFile(exportPath,'utf8'));check(capture.rawDocuments.length>=1,'complete CDP structure file');check(capture.captureComplete,'complete frame DOM and AX export');check(capture.nodes.some(n=>n.attributes?.id==='hidden'),'export includes hidden nodes');
 const shot=await call('page.screenshot',{tab,output:join(temporary,'viewport.png'),maxSide:640});check(shot.delivery==='file_only'&&!shot.data,'image not injected');check((await stat(shot.path)).size>0,'screenshot written');
 const namedShot=await call('page.screenshot',{tab,role:'button',name:'Load async',output:join(temporary,'named.png')});check(namedShot.width<200&&namedShot.height<100,'role/name screenshot selects element');
 const tiles=await call('page.screenshot',{tab,fullPage:true,output:join(temporary,'full.json'),maxSide:640,maxChars:14000});check(tiles.tileCount>=3,'long page tiled export');
 const id=crypto.randomUUID();const request={profile:'test',tab,selector:'#name',value:'once'};const once=await raw('page.fill',request,id);check(JSON.stringify(once)===JSON.stringify(await raw('page.fill',request,id)),'completed request deduplicated');check(!(await raw('page.fill',{...request,value:'different'},id)).ok,'ID collision rejected');
 const fresh=await call('page.snapshot',{tab});const navigated=await call('page.navigate',{tab,url:url+'/next',observe:true,until:{urlContains:'/next'},timeout:5});check(navigated.observation.conditionMet,'navigation completion observation');await new Promise(r=>setTimeout(r,300));check(!(await raw('page.click',{profile:'test',tab,snapshot:fresh.snapshot,ref:fresh.nodes.find(n=>n.name==='Load async').ref})).ok,'navigation invalidates refs');
 if(process.env.TEST_CLI){const cli=JSON.parse(process.env.TEST_CLI);const run=async(args,input='')=>{const child=spawn(cli[0],[...cli.slice(1),...args],{env:{...process.env,ISOLATOR_PIPE:testPipe,ISOLATOR_SOCKET:join(temporary,'automation.sock')},stdio:['pipe','pipe','pipe']});let out='';child.stdout.on('data',d=>out+=d);child.stdin.end(input);await new Promise(r=>child.on('close',r));return out.trim().split('\n').filter(Boolean).map(JSON.parse)};const list=await run(['profile','list']);check(list[0].ok,'CLI local IPC');const mcp=await run(['mcp','serve'],[{jsonrpc:'2.0',id:1,method:'initialize',params:{protocolVersion:'2025-11-25'}},{jsonrpc:'2.0',id:2,method:'tools/list'},{jsonrpc:'2.0',id:3,method:'tools/call',params:{name:'isolator_profiles',arguments:{operation:'profile.list',params:{}}}}].map(JSON.stringify).join('\n')+'\n');check(mcp.find(r=>r.id===2)?.result.tools.length===5,'compact MCP tools');check(mcp.find(r=>r.id===3)?.result.structuredContent.ok,'MCP bridge IPC');const vision=await run(['mcp','serve','--vision'],JSON.stringify({jsonrpc:'2.0',id:4,method:'tools/list'})+'\n');check(vision[0]?.result.tools.length===6,'vision tool requires explicit server opt-in');const rejected=await run(['mcp','serve','--vision'],JSON.stringify({jsonrpc:'2.0',id:5,method:'tools/call',params:{name:'isolator_image',arguments:{path:shot.path,vision:true}}})+'\n');check(rejected[0]?.result.isError,'image must belong to current MCP session');
 const client=spawn(cli[0],[...cli.slice(1),'mcp','serve','--vision'],{env:{...process.env,ISOLATOR_PIPE:testPipe,ISOLATOR_SOCKET:join(temporary,'automation.sock')},stdio:['pipe','pipe','pipe']});const replies=new Map();createInterface({input:client.stdout}).on('line',line=>{const r=JSON.parse(line);replies.get(r.id)?.(r);replies.delete(r.id);});const send=(method,params)=>new Promise(resolve=>{const id=crypto.randomUUID();replies.set(id,resolve);client.stdin.write(JSON.stringify({jsonrpc:'2.0',id,method,params})+'\n')});
 const imageShot=await send('tools/call',{name:'isolator_screenshot',arguments:{operation:'page.screenshot',params:{profile:'test',tab,output:join(temporary,'mcp.png'),maxSide:320}}});check(imageShot.result.structuredContent.ok,'MCP explicit image session capture');const image=await send('tools/call',{name:'isolator_image',arguments:{path:imageShot.result.structuredContent.result.path,vision:true}});check(image.result.content[0].type==='image'&&image.result.content[0].data.startsWith('iVBOR'),'explicit vision delivery');client.stdin.end();await new Promise(resolve=>client.on('close',resolve));}
 await call('page.close',{tab});check(!(await raw('page.snapshot',{profile:'test',tab})).ok,'closed page handled');
 console.log(JSON.stringify({passed:assertions,engine:argv.join(' ')}));
}finally{harness?.stdin.end();harness?.kill();chrome?.kill();for(const server of servers)server.close();await new Promise(r=>setTimeout(r,200));await rm(temporary,{recursive:true,force:true,maxRetries:20,retryDelay:250});}
