import Foundation

enum AppLanguage: String, CaseIterable, Identifiable {
    case zh
    case en
    case ja
    case ko
    case de
    case fr
    case ru

    var id: String { rawValue }

    var nativeName: String {
        switch self {
        case .zh: return "中文"
        case .en: return "English"
        case .ja: return "日本語"
        case .ko: return "한국어"
        case .de: return "Deutsch"
        case .fr: return "Français"
        case .ru: return "Русский"
        }
    }

    var localeIdentifier: String {
        switch self {
        case .zh: return "zh_Hans"
        case .en: return "en"
        case .ja: return "ja"
        case .ko: return "ko"
        case .de: return "de"
        case .fr: return "fr"
        case .ru: return "ru"
        }
    }

    static var preferred: AppLanguage {
        let codes = Locale.preferredLanguages.map { Locale(identifier: $0).language.languageCode?.identifier ?? $0 }
        for code in codes {
            if code.hasPrefix("zh") { return .zh }
            if code.hasPrefix("en") { return .en }
            if code.hasPrefix("ja") { return .ja }
            if code.hasPrefix("ko") { return .ko }
            if code.hasPrefix("de") { return .de }
            if code.hasPrefix("fr") { return .fr }
            if code.hasPrefix("ru") { return .ru }
        }
        return .zh
    }
}

@MainActor
final class Localization: ObservableObject {
    @Published var language: AppLanguage {
        didSet {
            UserDefaults.standard.set(language.rawValue, forKey: Self.storageKey)
        }
    }

    private static let storageKey = "AppLanguage"

    init() {
        if let raw = UserDefaults.standard.string(forKey: Self.storageKey),
           let saved = AppLanguage(rawValue: raw) {
            self.language = saved
        } else {
            self.language = .preferred
        }
    }

    var locale: Locale {
        Locale(identifier: language.localeIdentifier)
    }

    func t(_ key: String) -> String {
        Self.translations[language]?[key] ?? Self.translations[.en]?[key] ?? key
    }

    func format(_ key: String, _ args: CVarArg...) -> String {
        String(format: t(key), locale: locale, arguments: args)
    }

    private static let translations: [AppLanguage: [String: String]] = [
        .zh: [
            "app.name": "浏览器多开",
            "common.cancel": "取消",
            "common.confirm": "确定",
            "common.delete": "删除",
            "common.close": "关闭",
            "common.start": "启动",
            "common.later": "稍后",
            "language": "语言",
            "profile.default_name": "环境%d",
            "profile.display_name": "环境%d - %@",
            "empty.title": "还没有环境",
            "empty.subtitle": "点击工具栏 + 添加一个",
            "toolbar.add": "添加环境",
            "toolbar.stop_all": "全部关闭",
            "context.rename": "重命名",
            "context.delete": "删除",
            "delete.title": "确认删除",
            "delete.message": "将把「%@」的数据移到废纸篓。\n当前数据大小：%@\n请输入环境名称确认。",
            "delete.confirm_placeholder": "输入环境名称",
            "status.starting": "启动中",
            "status.stopping": "关闭中",
            "status.running": "运行中",
            "status.stopped": "未启动",
            "error.start_failed": "启动失败",
            "error.delete_failed": "删除失败",
            "error.profile_message": "%@\n%@",
            "meta.port": "端口 %d",
            "details.folder": "环境目录",
            "details.profile_path": "数据路径",
            "details.port": "调试端口",
            "details.cpu": "CPU 核心",
            "details.memory": "内存",
            "date.today": "今天",
            "date.yesterday": "昨天",
            "date.days_ago": "%d天前",
            "date.month_day": "%d月%d日",
            "rename.title": "重命名",
            "rename.hint": "自定义名称，方便识别",
            "rename.placeholder": "为此环境命名",
            "menu.open_panel": "打开管理面板",
            "menu.check_updates": "检查更新",
            "menu.close_all_quit": "全部关闭并退出",
            "menu.quit": "退出",
            "settings.title": "设置",
            "settings.browser": "浏览器",
            "settings.chrome_status": "Chrome 状态",
            "settings.ready": "可用",
            "settings.not_installed": "未安装",
            "settings.chrome_version": "Chrome 版本",
            "settings.unknown": "未知",
            "settings.open_chrome_folder": "打开 Chrome 文件夹",
            "settings.redownload_chrome": "重新下载 Chrome",
            "settings.data": "数据",
            "settings.data_path": "数据目录",
            "settings.open_data_folder": "打开数据目录",
            "settings.open_profiles_folder": "打开环境目录",
            "settings.copy_path": "复制路径",
            "settings.preferences": "偏好",
            "settings.show_advanced": "显示高级详情",
            "settings.help_updates": "帮助与更新",
            "settings.app_version": "当前版本",
            "settings.view_releases": "查看 Releases",
            "settings.contact": "联系方式",
            "settings.help_hint": "检查更新会对比 GitHub 最新 Release；需要下载或查看变更时会打开 Releases 页面。\n\n图标字体：MiSans。",
            "settings.contact_title": "BrowserIsolator 联系信息",
            "settings.contact_body": "作者：Lucas\n\n功能建议与问题反馈：\nhttps://github.com/vivalucas/BrowserIsolator/issues\n\n邮箱：lucas6.zju@vip.163.com",
            "settings.open_issues": "打开 Issues",
            "settings.copy_email": "复制邮箱",
            "inspector.empty_title": "选择一个环境",
            "inspector.empty_subtitle": "详情会显示在这里",
            "inspector.basic": "基础信息",
            "inspector.advanced": "高级信息",
            "inspector.actions": "操作",
            "inspector.error": "错误",
            "inspector.retry": "重试",
            "inspector.clear_error": "清除",
            "inspector.open_profile_folder": "打开此环境目录",
            "inspector.copy_profile_path": "复制环境路径",
            "inspector.last_used": "最近使用",
            "update.title": "检查更新",
            "update.up_to_date": "当前已是最新版本",
            "update.available_title": "发现新版本",
            "update.available_message": "最新版本: %@\n当前版本: %@",
            "update.download": "前往下载",
            "update.failed": "无法连接服务器，请检查网络后重试",
            "quit.title": "确认退出",
            "quit.confirm": "关闭并退出",
            "quit.message": "还有 %d 个环境正在运行，退出将自动关闭所有环境。",
            "download.title": "首次使用，正在下载浏览器",
            "download.preparing": "准备中...",
            "download.progress": "下载中...（约 237MB）",
            "download.installing": "正在安装...",
            "download.verifying": "正在校验...",
            "download.failed": "下载失败",
            "download.manual_title": "你也可以手动安装浏览器：",
            "download.manual_steps": "1. 下载 Chrome：https://www.google.com/chrome/\n2. 双击 dmg，将「Google Chrome.app」\n   拖入下方目标文件夹",
            "download.open_folder": "打开目标文件夹",
            "download.copy_error": "复制错误",
            "download.use_existing": "继续使用当前 Chrome",
            "download.retry": "重试下载"
        ],
        .en: [
            "app.name": "Browser Isolator",
            "common.cancel": "Cancel",
            "common.confirm": "OK",
            "common.delete": "Delete",
            "common.close": "Close",
            "common.start": "Start",
            "common.later": "Later",
            "language": "Language",
            "profile.default_name": "Environment %d",
            "profile.display_name": "Environment %d - %@",
            "empty.title": "No environments yet",
            "empty.subtitle": "Click + in the toolbar to add one",
            "toolbar.add": "Add Environment",
            "toolbar.stop_all": "Close All",
            "context.rename": "Rename",
            "context.delete": "Delete",
            "delete.title": "Confirm Delete",
            "delete.message": "Move data for \"%@\" to Trash.\nCurrent data size: %@\nType the environment name to confirm.",
            "delete.confirm_placeholder": "Type environment name",
            "status.starting": "Starting",
            "status.stopping": "Closing",
            "status.running": "Running",
            "status.stopped": "Stopped",
            "error.start_failed": "Start Failed",
            "error.delete_failed": "Delete Failed",
            "error.profile_message": "%@\n%@",
            "meta.port": "Port %d",
            "details.folder": "Folder",
            "details.profile_path": "Data path",
            "details.port": "Debug port",
            "details.cpu": "CPU cores",
            "details.memory": "Memory",
            "date.today": "Today",
            "date.yesterday": "Yesterday",
            "date.days_ago": "%d days ago",
            "date.month_day": "%d/%d",
            "rename.title": "Rename",
            "rename.hint": "Add a custom name for recognition",
            "rename.placeholder": "Name this environment",
            "menu.open_panel": "Open Panel",
            "menu.check_updates": "Check for Updates",
            "menu.close_all_quit": "Close All and Quit",
            "menu.quit": "Quit",
            "settings.title": "Settings",
            "settings.browser": "Browser",
            "settings.chrome_status": "Chrome Status",
            "settings.ready": "Ready",
            "settings.not_installed": "Not Installed",
            "settings.chrome_version": "Chrome Version",
            "settings.unknown": "Unknown",
            "settings.open_chrome_folder": "Open Chrome Folder",
            "settings.redownload_chrome": "Redownload Chrome",
            "settings.data": "Data",
            "settings.data_path": "Data Folder",
            "settings.open_data_folder": "Open Data Folder",
            "settings.open_profiles_folder": "Open Profiles Folder",
            "settings.copy_path": "Copy Path",
            "settings.preferences": "Preferences",
            "settings.show_advanced": "Show advanced details",
            "settings.help_updates": "Help & Updates",
            "settings.app_version": "Current Version",
            "settings.view_releases": "View Releases",
            "settings.contact": "Contact",
            "settings.help_hint": "Update checks compare against the latest GitHub Release. Downloads and changelogs open the Releases page.\n\nIcon font: MiSans.",
            "settings.contact_title": "BrowserIsolator Contact Info",
            "settings.contact_body": "Author: Lucas\n\nBug reports & feature requests:\nhttps://github.com/vivalucas/BrowserIsolator/issues\n\nEmail: lucas6.zju@vip.163.com",
            "settings.open_issues": "Open Issues",
            "settings.copy_email": "Copy Email",
            "inspector.empty_title": "Select an Environment",
            "inspector.empty_subtitle": "Details will appear here",
            "inspector.basic": "Basic Info",
            "inspector.advanced": "Advanced Info",
            "inspector.actions": "Actions",
            "inspector.error": "Error",
            "inspector.retry": "Retry",
            "inspector.clear_error": "Clear",
            "inspector.open_profile_folder": "Open Profile Folder",
            "inspector.copy_profile_path": "Copy Profile Path",
            "inspector.last_used": "Last Used",
            "update.title": "Check for Updates",
            "update.up_to_date": "You are already on the latest version",
            "update.available_title": "New Version Available",
            "update.available_message": "Latest: %@\nCurrent: %@",
            "update.download": "Download",
            "update.failed": "Could not connect to the server. Check your network and try again.",
            "quit.title": "Confirm Quit",
            "quit.confirm": "Close and Quit",
            "quit.message": "%d environments are still running. Quitting will close them all.",
            "download.title": "Downloading browser for first use",
            "download.preparing": "Preparing...",
            "download.progress": "Downloading... (about 237 MB)",
            "download.installing": "Installing...",
            "download.verifying": "Verifying...",
            "download.failed": "Download failed",
            "download.manual_title": "You can also install the browser manually:",
            "download.manual_steps": "1. Download Chrome: https://www.google.com/chrome/\n2. Open the DMG and move \"Google Chrome.app\"\n   into the target folder below",
            "download.open_folder": "Open Target Folder",
            "download.copy_error": "Copy Error",
            "download.use_existing": "Use Existing Chrome",
            "download.retry": "Retry Download"
        ],
        .ja: [
            "app.name": "ブラウザ分離",
            "common.cancel": "キャンセル",
            "common.confirm": "OK",
            "common.delete": "削除",
            "common.close": "閉じる",
            "common.start": "起動",
            "common.later": "後で",
            "language": "言語",
            "profile.default_name": "環境%d",
            "profile.display_name": "環境%d - %@",
            "empty.title": "環境はまだありません",
            "empty.subtitle": "ツールバーの + で追加",
            "toolbar.add": "環境を追加",
            "toolbar.stop_all": "すべて閉じる",
            "context.rename": "名前を変更",
            "context.delete": "削除",
            "delete.title": "削除の確認",
            "delete.message": "「%@」のデータをゴミ箱へ移動します。\n現在のデータサイズ：%@\n環境名を入力して確認してください。",
            "delete.confirm_placeholder": "環境名を入力",
            "status.starting": "起動中",
            "status.stopping": "終了中",
            "status.running": "実行中",
            "status.stopped": "停止中",
            "error.start_failed": "起動に失敗しました",
            "error.delete_failed": "削除に失敗しました",
            "error.profile_message": "%@\n%@",
            "meta.port": "ポート %d",
            "details.folder": "フォルダ",
            "details.profile_path": "データパス",
            "details.port": "デバッグポート",
            "details.cpu": "CPU コア",
            "details.memory": "メモリ",
            "date.today": "今日",
            "date.yesterday": "昨日",
            "date.days_ago": "%d日前",
            "date.month_day": "%d月%d日",
            "rename.title": "名前を変更",
            "rename.hint": "識別しやすい名前を付けます",
            "rename.placeholder": "この環境の名前",
            "menu.open_panel": "管理パネルを開く",
            "menu.check_updates": "アップデートを確認",
            "menu.close_all_quit": "すべて閉じて終了",
            "menu.quit": "終了",
            "settings.title": "設定",
            "settings.browser": "ブラウザ",
            "settings.chrome_status": "Chrome 状態",
            "settings.ready": "利用可能",
            "settings.not_installed": "未インストール",
            "settings.chrome_version": "Chrome バージョン",
            "settings.unknown": "不明",
            "settings.open_chrome_folder": "Chrome フォルダを開く",
            "settings.redownload_chrome": "Chrome を再ダウンロード",
            "settings.data": "データ",
            "settings.data_path": "データフォルダ",
            "settings.open_data_folder": "データフォルダを開く",
            "settings.open_profiles_folder": "環境フォルダを開く",
            "settings.copy_path": "パスをコピー",
            "settings.preferences": "環境設定",
            "settings.show_advanced": "詳細情報を表示",
            "inspector.empty_title": "環境を選択",
            "inspector.empty_subtitle": "ここに詳細が表示されます",
            "inspector.basic": "基本情報",
            "inspector.advanced": "詳細情報",
            "inspector.actions": "操作",
            "inspector.error": "エラー",
            "inspector.retry": "再試行",
            "inspector.clear_error": "クリア",
            "inspector.open_profile_folder": "この環境フォルダを開く",
            "inspector.copy_profile_path": "環境パスをコピー",
            "inspector.last_used": "最終使用",
            "update.title": "アップデート確認",
            "update.up_to_date": "現在のバージョンは最新です",
            "update.available_title": "新しいバージョンがあります",
            "update.available_message": "最新: %@\n現在: %@",
            "update.download": "ダウンロード",
            "update.failed": "サーバーに接続できません。ネットワークを確認してください。",
            "quit.title": "終了の確認",
            "quit.confirm": "閉じて終了",
            "quit.message": "%d 個の環境が実行中です。終了するとすべて閉じます。",
            "download.title": "初回使用のためブラウザをダウンロード中",
            "download.preparing": "準備中...",
            "download.progress": "ダウンロード中...（約 237 MB）",
            "download.installing": "インストール中...",
            "download.verifying": "検証中...",
            "download.failed": "ダウンロード失敗",
            "download.manual_title": "手動でブラウザをインストールすることもできます：",
            "download.manual_steps": "1. Chrome をダウンロード：https://www.google.com/chrome/\n2. DMG を開き、「Google Chrome.app」を\n   下の対象フォルダへ移動",
            "download.open_folder": "対象フォルダを開く",
            "download.copy_error": "エラーをコピー",
            "download.use_existing": "現在の Chrome を使用",
            "download.retry": "再試行"
        ],
        .ko: [
            "app.name": "브라우저 분리",
            "common.cancel": "취소",
            "common.confirm": "확인",
            "common.delete": "삭제",
            "common.close": "닫기",
            "common.start": "시작",
            "common.later": "나중에",
            "language": "언어",
            "profile.default_name": "환경 %d",
            "profile.display_name": "환경 %d - %@",
            "empty.title": "아직 환경이 없습니다",
            "empty.subtitle": "툴바의 + 버튼으로 추가하세요",
            "toolbar.add": "환경 추가",
            "toolbar.stop_all": "모두 닫기",
            "context.rename": "이름 변경",
            "context.delete": "삭제",
            "delete.title": "삭제 확인",
            "delete.message": "\"%@\" 데이터를 휴지통으로 이동합니다.\n현재 데이터 크기: %@\n환경 이름을 입력해 확인하세요.",
            "delete.confirm_placeholder": "환경 이름 입력",
            "status.starting": "시작 중",
            "status.stopping": "닫는 중",
            "status.running": "실행 중",
            "status.stopped": "중지됨",
            "error.start_failed": "시작 실패",
            "error.delete_failed": "삭제 실패",
            "error.profile_message": "%@\n%@",
            "meta.port": "포트 %d",
            "details.folder": "폴더",
            "details.profile_path": "데이터 경로",
            "details.port": "디버그 포트",
            "details.cpu": "CPU 코어",
            "details.memory": "메모리",
            "date.today": "오늘",
            "date.yesterday": "어제",
            "date.days_ago": "%d일 전",
            "date.month_day": "%d월 %d일",
            "rename.title": "이름 변경",
            "rename.hint": "구분하기 쉬운 이름을 추가하세요",
            "rename.placeholder": "이 환경 이름",
            "menu.open_panel": "관리 패널 열기",
            "menu.check_updates": "업데이트 확인",
            "menu.close_all_quit": "모두 닫고 종료",
            "menu.quit": "종료",
            "settings.title": "설정",
            "settings.browser": "브라우저",
            "settings.chrome_status": "Chrome 상태",
            "settings.ready": "사용 가능",
            "settings.not_installed": "설치되지 않음",
            "settings.chrome_version": "Chrome 버전",
            "settings.unknown": "알 수 없음",
            "settings.open_chrome_folder": "Chrome 폴더 열기",
            "settings.redownload_chrome": "Chrome 다시 다운로드",
            "settings.data": "데이터",
            "settings.data_path": "데이터 폴더",
            "settings.open_data_folder": "데이터 폴더 열기",
            "settings.open_profiles_folder": "환경 폴더 열기",
            "settings.copy_path": "경로 복사",
            "settings.preferences": "환경설정",
            "settings.show_advanced": "고급 세부 정보 표시",
            "inspector.empty_title": "환경 선택",
            "inspector.empty_subtitle": "여기에 세부 정보가 표시됩니다",
            "inspector.basic": "기본 정보",
            "inspector.advanced": "고급 정보",
            "inspector.actions": "작업",
            "inspector.error": "오류",
            "inspector.retry": "다시 시도",
            "inspector.clear_error": "지우기",
            "inspector.open_profile_folder": "이 환경 폴더 열기",
            "inspector.copy_profile_path": "환경 경로 복사",
            "inspector.last_used": "마지막 사용",
            "update.title": "업데이트 확인",
            "update.up_to_date": "이미 최신 버전입니다",
            "update.available_title": "새 버전 발견",
            "update.available_message": "최신: %@\n현재: %@",
            "update.download": "다운로드",
            "update.failed": "서버에 연결할 수 없습니다. 네트워크를 확인하세요.",
            "quit.title": "종료 확인",
            "quit.confirm": "닫고 종료",
            "quit.message": "%d개의 환경이 실행 중입니다. 종료하면 모두 닫힙니다.",
            "download.title": "처음 사용을 위해 브라우저 다운로드 중",
            "download.preparing": "준비 중...",
            "download.progress": "다운로드 중... (약 237 MB)",
            "download.installing": "설치 중...",
            "download.verifying": "확인 중...",
            "download.failed": "다운로드 실패",
            "download.manual_title": "브라우저를 수동으로 설치할 수도 있습니다:",
            "download.manual_steps": "1. Chrome 다운로드: https://www.google.com/chrome/\n2. DMG를 열고 \"Google Chrome.app\"을\n   아래 대상 폴더로 이동",
            "download.open_folder": "대상 폴더 열기",
            "download.copy_error": "오류 복사",
            "download.use_existing": "현재 Chrome 사용",
            "download.retry": "다시 다운로드"
        ],
        .de: [
            "app.name": "Browser-Isolator",
            "common.cancel": "Abbrechen",
            "common.confirm": "OK",
            "common.delete": "Löschen",
            "common.close": "Schließen",
            "common.start": "Starten",
            "common.later": "Später",
            "language": "Sprache",
            "profile.default_name": "Umgebung %d",
            "profile.display_name": "Umgebung %d - %@",
            "empty.title": "Noch keine Umgebungen",
            "empty.subtitle": "Klicke auf + in der Symbolleiste",
            "toolbar.add": "Umgebung hinzufügen",
            "toolbar.stop_all": "Alle schließen",
            "context.rename": "Umbenennen",
            "context.delete": "Löschen",
            "delete.title": "Löschen bestätigen",
            "delete.message": "Daten für „%@“ in den Papierkorb verschieben.\nAktuelle Datengröße: %@\nGib den Umgebungsnamen zur Bestätigung ein.",
            "delete.confirm_placeholder": "Umgebungsnamen eingeben",
            "status.starting": "Startet",
            "status.stopping": "Schließt",
            "status.running": "Läuft",
            "status.stopped": "Gestoppt",
            "error.start_failed": "Start fehlgeschlagen",
            "error.delete_failed": "Löschen fehlgeschlagen",
            "error.profile_message": "%@\n%@",
            "meta.port": "Port %d",
            "details.folder": "Ordner",
            "details.profile_path": "Datenpfad",
            "details.port": "Debug-Port",
            "details.cpu": "CPU-Kerne",
            "details.memory": "Speicher",
            "date.today": "Heute",
            "date.yesterday": "Gestern",
            "date.days_ago": "vor %d Tagen",
            "date.month_day": "%d.%d.",
            "rename.title": "Umbenennen",
            "rename.hint": "Eigener Name zur besseren Erkennung",
            "rename.placeholder": "Diese Umgebung benennen",
            "menu.open_panel": "Panel öffnen",
            "menu.check_updates": "Nach Updates suchen",
            "menu.close_all_quit": "Alle schließen und beenden",
            "menu.quit": "Beenden",
            "settings.title": "Einstellungen",
            "settings.browser": "Browser",
            "settings.chrome_status": "Chrome-Status",
            "settings.ready": "Bereit",
            "settings.not_installed": "Nicht installiert",
            "settings.chrome_version": "Chrome-Version",
            "settings.unknown": "Unbekannt",
            "settings.open_chrome_folder": "Chrome-Ordner öffnen",
            "settings.redownload_chrome": "Chrome erneut laden",
            "settings.data": "Daten",
            "settings.data_path": "Datenordner",
            "settings.open_data_folder": "Datenordner öffnen",
            "settings.open_profiles_folder": "Profilordner öffnen",
            "settings.copy_path": "Pfad kopieren",
            "settings.preferences": "Einstellungen",
            "settings.show_advanced": "Erweiterte Details anzeigen",
            "inspector.empty_title": "Umgebung auswählen",
            "inspector.empty_subtitle": "Details erscheinen hier",
            "inspector.basic": "Basisinfos",
            "inspector.advanced": "Erweiterte Infos",
            "inspector.actions": "Aktionen",
            "inspector.error": "Fehler",
            "inspector.retry": "Erneut versuchen",
            "inspector.clear_error": "Löschen",
            "inspector.open_profile_folder": "Diesen Profilordner öffnen",
            "inspector.copy_profile_path": "Profilpfad kopieren",
            "inspector.last_used": "Letzte Nutzung",
            "update.title": "Nach Updates suchen",
            "update.up_to_date": "Du verwendest bereits die neueste Version",
            "update.available_title": "Neue Version verfügbar",
            "update.available_message": "Neueste: %@\nAktuell: %@",
            "update.download": "Herunterladen",
            "update.failed": "Keine Verbindung zum Server. Bitte Netzwerk prüfen.",
            "quit.title": "Beenden bestätigen",
            "quit.confirm": "Schließen und beenden",
            "quit.message": "%d Umgebungen laufen noch. Beim Beenden werden alle geschlossen.",
            "download.title": "Browser wird für die erste Nutzung geladen",
            "download.preparing": "Vorbereitung...",
            "download.progress": "Download läuft... (ca. 237 MB)",
            "download.installing": "Installation läuft...",
            "download.verifying": "Prüfung läuft...",
            "download.failed": "Download fehlgeschlagen",
            "download.manual_title": "Du kannst den Browser auch manuell installieren:",
            "download.manual_steps": "1. Chrome herunterladen: https://www.google.com/chrome/\n2. DMG öffnen und „Google Chrome.app“\n   in den Zielordner unten verschieben",
            "download.open_folder": "Zielordner öffnen",
            "download.copy_error": "Fehler kopieren",
            "download.use_existing": "Vorhandenes Chrome verwenden",
            "download.retry": "Erneut versuchen"
        ],
        .fr: [
            "app.name": "Isolateur de navigateur",
            "common.cancel": "Annuler",
            "common.confirm": "OK",
            "common.delete": "Supprimer",
            "common.close": "Fermer",
            "common.start": "Démarrer",
            "common.later": "Plus tard",
            "language": "Langue",
            "profile.default_name": "Environnement %d",
            "profile.display_name": "Environnement %d - %@",
            "empty.title": "Aucun environnement",
            "empty.subtitle": "Cliquez sur + dans la barre d'outils",
            "toolbar.add": "Ajouter un environnement",
            "toolbar.stop_all": "Tout fermer",
            "context.rename": "Renommer",
            "context.delete": "Supprimer",
            "delete.title": "Confirmer la suppression",
            "delete.message": "Déplacer les données de « %@ » vers la corbeille.\nTaille actuelle : %@\nSaisissez le nom de l'environnement pour confirmer.",
            "delete.confirm_placeholder": "Nom de l'environnement",
            "status.starting": "Démarrage",
            "status.stopping": "Fermeture",
            "status.running": "En cours",
            "status.stopped": "Arrêté",
            "error.start_failed": "Échec du démarrage",
            "error.delete_failed": "Échec de la suppression",
            "error.profile_message": "%@\n%@",
            "meta.port": "Port %d",
            "details.folder": "Dossier",
            "details.profile_path": "Chemin des données",
            "details.port": "Port de débogage",
            "details.cpu": "Coeurs CPU",
            "details.memory": "Mémoire",
            "date.today": "Aujourd'hui",
            "date.yesterday": "Hier",
            "date.days_ago": "il y a %d jours",
            "date.month_day": "%d/%d",
            "rename.title": "Renommer",
            "rename.hint": "Ajoutez un nom pour mieux l'identifier",
            "rename.placeholder": "Nom de cet environnement",
            "menu.open_panel": "Ouvrir le panneau",
            "menu.check_updates": "Rechercher des mises à jour",
            "menu.close_all_quit": "Tout fermer et quitter",
            "menu.quit": "Quitter",
            "settings.title": "Réglages",
            "settings.browser": "Navigateur",
            "settings.chrome_status": "État de Chrome",
            "settings.ready": "Prêt",
            "settings.not_installed": "Non installé",
            "settings.chrome_version": "Version de Chrome",
            "settings.unknown": "Inconnu",
            "settings.open_chrome_folder": "Ouvrir le dossier Chrome",
            "settings.redownload_chrome": "Retélécharger Chrome",
            "settings.data": "Données",
            "settings.data_path": "Dossier de données",
            "settings.open_data_folder": "Ouvrir le dossier de données",
            "settings.open_profiles_folder": "Ouvrir le dossier des profils",
            "settings.copy_path": "Copier le chemin",
            "settings.preferences": "Préférences",
            "settings.show_advanced": "Afficher les détails avancés",
            "inspector.empty_title": "Sélectionnez un environnement",
            "inspector.empty_subtitle": "Les détails s'afficheront ici",
            "inspector.basic": "Informations de base",
            "inspector.advanced": "Informations avancées",
            "inspector.actions": "Actions",
            "inspector.error": "Erreur",
            "inspector.retry": "Réessayer",
            "inspector.clear_error": "Effacer",
            "inspector.open_profile_folder": "Ouvrir ce dossier de profil",
            "inspector.copy_profile_path": "Copier le chemin du profil",
            "inspector.last_used": "Dernière utilisation",
            "update.title": "Rechercher des mises à jour",
            "update.up_to_date": "Vous utilisez déjà la dernière version",
            "update.available_title": "Nouvelle version disponible",
            "update.available_message": "Dernière: %@\nActuelle: %@",
            "update.download": "Télécharger",
            "update.failed": "Impossible de se connecter au serveur. Vérifiez le réseau.",
            "quit.title": "Confirmer la fermeture",
            "quit.confirm": "Fermer et quitter",
            "quit.message": "%d environnements sont encore en cours. Quitter les fermera tous.",
            "download.title": "Téléchargement du navigateur pour la première utilisation",
            "download.preparing": "Préparation...",
            "download.progress": "Téléchargement... (environ 237 Mo)",
            "download.installing": "Installation...",
            "download.verifying": "Vérification...",
            "download.failed": "Échec du téléchargement",
            "download.manual_title": "Vous pouvez aussi installer le navigateur manuellement :",
            "download.manual_steps": "1. Téléchargez Chrome : https://www.google.com/chrome/\n2. Ouvrez le DMG et déplacez « Google Chrome.app »\n   dans le dossier cible ci-dessous",
            "download.open_folder": "Ouvrir le dossier cible",
            "download.copy_error": "Copier l'erreur",
            "download.use_existing": "Utiliser Chrome existant",
            "download.retry": "Réessayer"
        ],
        .ru: [
            "app.name": "Изолятор браузера",
            "common.cancel": "Отмена",
            "common.confirm": "OK",
            "common.delete": "Удалить",
            "common.close": "Закрыть",
            "common.start": "Запустить",
            "common.later": "Позже",
            "language": "Язык",
            "profile.default_name": "Среда %d",
            "profile.display_name": "Среда %d - %@",
            "empty.title": "Сред пока нет",
            "empty.subtitle": "Нажмите + на панели инструментов",
            "toolbar.add": "Добавить среду",
            "toolbar.stop_all": "Закрыть все",
            "context.rename": "Переименовать",
            "context.delete": "Удалить",
            "delete.title": "Подтвердите удаление",
            "delete.message": "Переместить данные «%@» в корзину.\nТекущий размер данных: %@\nВведите имя среды для подтверждения.",
            "delete.confirm_placeholder": "Введите имя среды",
            "status.starting": "Запуск",
            "status.stopping": "Закрытие",
            "status.running": "Работает",
            "status.stopped": "Остановлена",
            "error.start_failed": "Не удалось запустить",
            "error.delete_failed": "Не удалось удалить",
            "error.profile_message": "%@\n%@",
            "meta.port": "Порт %d",
            "details.folder": "Папка",
            "details.profile_path": "Путь данных",
            "details.port": "Debug-порт",
            "details.cpu": "Ядра CPU",
            "details.memory": "Память",
            "date.today": "Сегодня",
            "date.yesterday": "Вчера",
            "date.days_ago": "%d дн. назад",
            "date.month_day": "%d.%d",
            "rename.title": "Переименовать",
            "rename.hint": "Добавьте имя для удобного распознавания",
            "rename.placeholder": "Имя этой среды",
            "menu.open_panel": "Открыть панель",
            "menu.check_updates": "Проверить обновления",
            "menu.close_all_quit": "Закрыть все и выйти",
            "menu.quit": "Выйти",
            "settings.title": "Настройки",
            "settings.browser": "Браузер",
            "settings.chrome_status": "Состояние Chrome",
            "settings.ready": "Готов",
            "settings.not_installed": "Не установлен",
            "settings.chrome_version": "Версия Chrome",
            "settings.unknown": "Неизвестно",
            "settings.open_chrome_folder": "Открыть папку Chrome",
            "settings.redownload_chrome": "Скачать Chrome заново",
            "settings.data": "Данные",
            "settings.data_path": "Папка данных",
            "settings.open_data_folder": "Открыть папку данных",
            "settings.open_profiles_folder": "Открыть папку профилей",
            "settings.copy_path": "Скопировать путь",
            "settings.preferences": "Параметры",
            "settings.show_advanced": "Показывать расширенные детали",
            "inspector.empty_title": "Выберите среду",
            "inspector.empty_subtitle": "Подробности появятся здесь",
            "inspector.basic": "Основная информация",
            "inspector.advanced": "Расширенная информация",
            "inspector.actions": "Действия",
            "inspector.error": "Ошибка",
            "inspector.retry": "Повторить",
            "inspector.clear_error": "Очистить",
            "inspector.open_profile_folder": "Открыть папку этой среды",
            "inspector.copy_profile_path": "Скопировать путь среды",
            "inspector.last_used": "Последнее использование",
            "update.title": "Проверить обновления",
            "update.up_to_date": "У вас уже последняя версия",
            "update.available_title": "Доступна новая версия",
            "update.available_message": "Последняя: %@\nТекущая: %@",
            "update.download": "Скачать",
            "update.failed": "Не удалось подключиться к серверу. Проверьте сеть.",
            "quit.title": "Подтвердите выход",
            "quit.confirm": "Закрыть и выйти",
            "quit.message": "Еще работает сред: %d. При выходе все они будут закрыты.",
            "download.title": "Загрузка браузера для первого запуска",
            "download.preparing": "Подготовка...",
            "download.progress": "Загрузка... (около 237 МБ)",
            "download.installing": "Установка...",
            "download.verifying": "Проверка...",
            "download.failed": "Ошибка загрузки",
            "download.manual_title": "Браузер также можно установить вручную:",
            "download.manual_steps": "1. Скачайте Chrome: https://www.google.com/chrome/\n2. Откройте DMG и переместите «Google Chrome.app»\n   в целевую папку ниже",
            "download.open_folder": "Открыть целевую папку",
            "download.copy_error": "Скопировать ошибку",
            "download.use_existing": "Использовать текущий Chrome",
            "download.retry": "Повторить загрузку"
        ]
    ]
}
