import Foundation

enum AppLanguage: String, CaseIterable, Identifiable {
    case zh
    case en
    case ja

    var id: String { rawValue }

    var nativeName: String {
        switch self {
        case .zh: return "中文"
        case .en: return "English"
        case .ja: return "日本語"
        }
    }

    var localeIdentifier: String {
        switch self {
        case .zh: return "zh_Hans"
        case .en: return "en"
        case .ja: return "ja"
        }
    }

    static var preferred: AppLanguage {
        let codes = Locale.preferredLanguages.map { Locale(identifier: $0).language.languageCode?.identifier ?? $0 }
        for code in codes {
            if code.hasPrefix("zh") { return .zh }
            if code.hasPrefix("en") { return .en }
            if code.hasPrefix("ja") { return .ja }
        }
        return .zh
    }
}

@MainActor
final class Localization: ObservableObject {
    @Published var language: AppLanguage {
        didSet {
            UserDefaults.standard.set(language.rawValue, forKey: Self.storageKey)
        }
    }

    private static let storageKey = "AppLanguage"

    init() {
        if let raw = UserDefaults.standard.string(forKey: Self.storageKey),
           let saved = AppLanguage(rawValue: raw) {
            self.language = saved
        } else {
            self.language = .preferred
        }
    }

    var locale: Locale {
        Locale(identifier: language.localeIdentifier)
    }

    func t(_ key: String) -> String {
        Self.supplementalTranslations[language]?[key] ?? Self.translations[language]?[key] ?? Self.supplementalTranslations[.en]?[key] ?? Self.translations[.en]?[key] ?? key
    }

    func format(_ key: String, _ args: CVarArg...) -> String {
        String(format: t(key), locale: locale, arguments: args)
    }

    private static let supplementalTranslations: [AppLanguage: [String: String]] = [
        .zh: ["details.browser_path": "浏览器程序路径",
            "settings.environment_modes": "采集与差异模式", "settings.environment_modes_hint": "新建环境默认开启采集，已有设置保持不变。采集允许本机工具连接环境；差异会调整网页读取的处理器与内存信息，仅在需要时开启。", "settings.environment_modes_summary": "采集 %d，差异 %d / 共 %d 个环境", "settings.environment_modes_manage": "管理模式", "settings.environment_modes_manage_title": "管理采集与差异模式", "settings.environment_modes_manage_description": "关闭运行中的环境后即可切换模式。批量操作只影响当前筛选结果中可修改的环境。", "settings.collector_mode": "采集模式", "settings.collector_variation_mode": "采集和差异模式", "settings.collector_enable_all": "启用采集", "settings.collector_disable_all": "关闭采集", "config_load.recovered_backup": "主配置读取失败，已从备份恢复。请检查环境和设置是否正确。", "config_load.recovered_disk": "配置与备份均不可用，已根据磁盘中的环境目录重建配置。名称、备注和模式设置可能需要重新填写。", "config_load.recovered_defaults": "配置与备份均不可用，且未找到已有环境，已恢复默认配置。", "config_load.corrupt_path": "损坏的配置已保存在：\n%@"
        ],
        .en: ["details.browser_path": "Browser executable path",
            "settings.environment_modes": "Collector & Variation Modes", "settings.environment_modes_hint": "New environments enable collection by default; existing settings stay unchanged. Collection lets local tools connect to an environment. Variation changes the processor and memory information seen by websites; enable it only when needed.", "settings.environment_modes_summary": "Collector %d, variation %d / %d environments", "settings.environment_modes_manage": "Manage Modes", "settings.environment_modes_manage_title": "Manage Collector & Variation Modes", "settings.environment_modes_manage_description": "Close running environments before changing modes. Bulk actions affect only editable environments in the current filtered results.", "settings.collector_mode": "Collector Mode", "settings.collector_variation_mode": "Collector & Variation", "settings.collector_enable_all": "Enable collection", "settings.collector_disable_all": "Disable collection", "config_load.recovered_backup": "The main configuration could not be read and was restored from backup. Check your environments and settings.", "config_load.recovered_disk": "Neither configuration file was usable. Environments were rebuilt from disk; names, notes, and mode settings may need to be restored.", "config_load.recovered_defaults": "Neither configuration file was usable and no existing environments were found. Defaults were restored.", "config_load.corrupt_path": "The damaged configuration was saved at:\n%@"
        ],
        .ja: ["details.browser_path": "ブラウザーの実行ファイル", "settings.appearance": "外観", "settings.appearance_system": "システム", "settings.appearance_light": "ライト", "settings.appearance_dark": "ダーク", "settings.environment_modes": "収集・差異モード", "settings.environment_modes_hint": "新規環境は収集が既定で有効です。既存の設定は変わりません。収集ではローカルツールが環境に接続できます。差異はサイトに表示されるプロセッサーとメモリの情報を変更します。必要な場合のみ有効にしてください。", "settings.environment_modes_summary": "収集 %d、差異 %d / 全 %d 環境", "settings.environment_modes_manage": "モードを管理", "settings.environment_modes_manage_title": "収集・差異モードの管理", "settings.environment_modes_manage_description": "モードを変更する前に実行中の環境を閉じてください。一括操作は現在の絞り込み結果のうち変更可能な環境だけに適用されます。", "settings.collector_mode": "収集モード", "settings.collector_variation_mode": "収集・差異モード", "settings.collector_enable_all": "収集を有効にする", "settings.collector_disable_all": "収集を無効にする", "config_load.recovered_backup": "メイン設定を読み込めなかったため、バックアップから復元しました。", "config_load.recovered_disk": "設定とバックアップを使用できないため、ディスク上の環境から再構築しました。名前、メモ、モードは再設定が必要な場合があります。", "config_load.recovered_defaults": "使用可能な設定や既存環境がないため、既定値に戻しました。", "config_load.corrupt_path": "破損した設定の保存先：\n%@"],
    ]

    private static let translations: [AppLanguage: [String: String]] = [
        .zh: [
            "app.name": "浏览器多开",
            "common.cancel": "取消",
            "common.confirm": "确定",
            "common.delete": "删除",
            "common.close": "关闭",
            "common.start": "启动",
            "common.later": "稍后",
            "language": "语言",
            "profile.default_name": "环境%d",
            "profile.display_name": "环境%d - %@",
            "empty.title": "还没有环境",
            "empty.subtitle": "点击工具栏 + 添加一个",
            "toolbar.add": "添加环境",
            "toolbar.stop_all": "全部关闭",
            "context.rename": "重命名",
            "context.delete": "删除",
            "delete.title": "确认删除",
            "delete.message": "将把「%@」的数据移到废纸篓。\n当前数据大小：%@\n请输入 %@ 确认。",
            "delete.confirm_placeholder": "Delete",
            "status.starting": "启动中",
            "status.stopping": "关闭中",
            "status.running": "运行中",
            "status.stopped": "未启动",
            "error.start_failed": "启动失败",
            "error.delete_failed": "删除失败",
            "error.profile_message": "%@\n%@",
            "config_save.title": "配置保存失败",
            "config_load.title": "配置文件已损坏",
            "config_load.message": "配置文件读取失败，已恢复默认配置。",
            "config_load.message_with_backup": "配置文件读取失败，损坏副本已保存在：\n%@",
            "meta.port": "端口 %d",
            "details.folder": "环境目录",
            "details.profile_path": "数据路径",
            "details.run_mode": "运行模式",
            "details.port": "调试端口",
            "details.cpu": "CPU 核心",
            "details.memory": "内存",
            "date.today": "今天",
            "date.yesterday": "昨天",
            "date.days_ago": "%d天前",
            "date.month_day": "%d月%d日",
            "rename.title": "重命名",
            "rename.hint": "自定义名称，方便识别",
            "rename.placeholder": "为此环境命名",
            "context.note": "备注",
            "note.hint": "纯文本备注，最多 120 个 Unicode 字符",
            "note.placeholder": "输入备注",
            "menu.open_panel": "打开管理面板",
            "menu.check_updates": "检查更新",
            "menu.close_all_quit": "全部关闭并退出",
            "menu.quit": "退出",
            "settings.title": "设置",
            "settings.browser": "浏览器",
            "settings.chrome_status": "Chrome 状态",
            "settings.ready": "可用",
            "settings.not_installed": "未安装",
            "settings.chrome_version": "Chrome 版本",
            "settings.unknown": "未知",
            "settings.open_chrome_folder": "打开安装目录",
            "settings.redownload_chrome": "重新下载",
            "settings.redownload_confirm_title": "重新下载 Chrome？",
            "settings.redownload_confirm_message": "这会重新下载并安装 BrowserIsolator 使用的 Chrome。下载期间浏览器环境不可用。",
            "settings.data": "数据",
            "settings.data_path": "数据目录",
            "settings.open_data_folder": "打开数据目录",
            "settings.open_profiles_folder": "打开环境目录",
            "settings.copy_path": "复制路径",
            "settings.preferences": "偏好",
            "settings.show_advanced": "显示高级详情",
            "settings.external_links": "外部链接",
            "settings.open_to": "打开到",
            "settings.set_default_browser": "设为默认浏览器",
            "settings.fingerprint_mode": "差异模式",
            "settings.fingerprint_profiles": "环境",
            "settings.fingerprint_hint": "关闭时使用基础模式；开启后下次启动进入差异模式，启用调试端口和 navigator 注入",
            "settings.fingerprint_locked": "运行中的环境需要关闭后再切换",
            "settings.fingerprint_summary": "已启用 %d / %d 个环境",
            "settings.fingerprint_manage": "管理差异模式",
            "settings.fingerprint_manage_title": "管理差异模式",
            "settings.fingerprint_manage_description": "差异模式会在下次启动时启用调试端口并注入 hardwareConcurrency/deviceMemory；运行中的环境需要关闭后才能修改。",
            "settings.fingerprint_search_placeholder": "搜索环境",
            "settings.fingerprint_editable_only": "只显示可编辑环境",
            "settings.fingerprint_empty_profiles": "还没有环境",
            "settings.fingerprint_no_results": "没有匹配的环境",
            "settings.fingerprint_no_editable": "当前没有可编辑环境",
            "settings.fingerprint_locked_starting": "启动中，关闭后可修改",
            "settings.fingerprint_locked_running": "运行中，关闭后可修改",
            "settings.fingerprint_locked_stopping": "关闭中，完成后可修改",
            "settings.fingerprint_editable_status": "可修改，当前为%@",
            "settings.basic_mode": "基础模式",
            "settings.variation_mode": "差异模式",
            "settings.appearance": "外观",
            "settings.appearance_system": "跟随系统",
            "settings.appearance_light": "浅色",
            "settings.appearance_dark": "深色",
            "settings.about_support": "关于与支持",
            "settings.version_group": "版本与更新",
            "settings.author_group": "作者",
            "settings.feedback_group": "反馈",
            "settings.app_version": "当前版本",
            "settings.view_releases": "查看发布页",
            "settings.author": "作者",
            "settings.email": "邮箱",
            "settings.open_issues": "查看 Issues",
            "settings.copy_email": "复制邮箱",
            "external_link.title": "暂时无法打开链接",
            "external_link.message": "浏览器环境还没准备好。你可以稍后重试，或先复制这个链接：\n%@",
            "external_link.no_profile_message": "当前没有可用环境。请先创建或选择一个环境，再重试这个链接：\n%@",
            "external_link.copy": "复制链接",
            "inspector.empty_title": "选择一个环境",
            "inspector.empty_subtitle": "详情会显示在这里",
            "inspector.basic": "基础信息",
            "inspector.advanced": "高级信息",
            "inspector.actions": "操作",
            "inspector.error": "错误",
            "inspector.retry": "重试",
            "inspector.clear_error": "清除",
            "inspector.open_profile_folder": "打开此环境目录",
            "inspector.copy_profile_path": "复制环境路径",
            "inspector.last_used": "最近使用",
            "update.title": "检查更新",
            "update.up_to_date": "当前已是最新版本",
            "update.available_title": "发现新版本",
            "update.available_message": "最新版本: %@\n当前版本: %@",
            "update.download": "前往发布页",
            "update.failed": "无法连接服务器，请检查网络后重试",
            "quit.title": "确认退出",
            "quit.confirm": "关闭并退出",
            "quit.message": "还有 %d 个环境正在运行，退出将自动关闭所有环境。",
            "download.title": "首次使用，正在下载浏览器",
            "download.preparing": "准备中...",
            "download.progress": "下载中...（约 237MB）",
            "download.installing": "正在安装...",
            "download.verifying": "正在校验...",
            "download.failed": "下载失败",
            "download.manual_title": "你也可以手动安装浏览器：",
            "download.manual_steps": "1. 下载 Chrome：https://www.google.com/chrome/\n2. 双击 dmg，将「Google Chrome.app」\n   拖入下方目标文件夹",
            "download.open_folder": "打开目标文件夹",
            "download.copy_error": "复制错误",
            "download.use_existing": "继续使用当前 Chrome",
            "download.retry": "重试下载"
        ],
        .en: [
            "app.name": "Browser Isolator",
            "common.cancel": "Cancel",
            "common.confirm": "OK",
            "common.delete": "Delete",
            "common.close": "Close",
            "common.start": "Start",
            "common.later": "Later",
            "language": "Language",
            "profile.default_name": "Environment %d",
            "profile.display_name": "Environment %d - %@",
            "empty.title": "No environments yet",
            "empty.subtitle": "Click + in the toolbar to add one",
            "toolbar.add": "Add Environment",
            "toolbar.stop_all": "Close All",
            "context.rename": "Rename",
            "context.delete": "Delete",
            "delete.title": "Confirm Delete",
            "delete.message": "Move data for \"%@\" to Trash.\nCurrent data size: %@\nType %@ to confirm.",
            "delete.confirm_placeholder": "Delete",
            "status.starting": "Starting",
            "status.stopping": "Closing",
            "status.running": "Running",
            "status.stopped": "Stopped",
            "error.start_failed": "Start Failed",
            "error.delete_failed": "Delete Failed",
            "error.profile_message": "%@\n%@",
            "config_save.title": "Save Failed",
            "config_load.title": "Config File Corrupted",
            "config_load.message": "The config file could not be read. A clean default configuration was loaded.",
            "config_load.message_with_backup": "The config file could not be read. The corrupted copy was saved to:\n%@",
            "meta.port": "Port %d",
            "details.folder": "Folder",
            "details.profile_path": "Data path",
            "details.run_mode": "Run mode",
            "details.port": "Debug port",
            "details.cpu": "CPU cores",
            "details.memory": "Memory",
            "date.today": "Today",
            "date.yesterday": "Yesterday",
            "date.days_ago": "%d days ago",
            "date.month_day": "%d/%d",
            "rename.title": "Rename",
            "rename.hint": "Add a custom name for recognition",
            "rename.placeholder": "Name this environment",
            "context.note": "Note",
            "note.hint": "Plain text only, up to 120 Unicode characters",
            "note.placeholder": "Enter a note",
            "menu.open_panel": "Open Panel",
            "menu.check_updates": "Check for Updates",
            "menu.close_all_quit": "Close All and Quit",
            "menu.quit": "Quit",
            "settings.title": "Settings",
            "settings.browser": "Browser",
            "settings.chrome_status": "Chrome Status",
            "settings.ready": "Ready",
            "settings.not_installed": "Not Installed",
            "settings.chrome_version": "Chrome Version",
            "settings.unknown": "Unknown",
            "settings.open_chrome_folder": "Open Location",
            "settings.redownload_chrome": "Download Again",
            "settings.redownload_confirm_title": "Redownload Chrome?",
            "settings.redownload_confirm_message": "This will redownload and install the Chrome copy used by BrowserIsolator. Browser environments will be unavailable during the download.",
            "settings.data": "Data",
            "settings.data_path": "Data Folder",
            "settings.open_data_folder": "Open Data Folder",
            "settings.open_profiles_folder": "Open Profiles",
            "settings.copy_path": "Copy Path",
            "settings.preferences": "Preferences",
            "settings.show_advanced": "Show advanced details",
            "settings.external_links": "External Links",
            "settings.open_to": "Open in",
            "settings.set_default_browser": "Make Default",
            "settings.fingerprint_mode": "Variation Mode",
            "settings.fingerprint_profiles": "Environments",
            "settings.fingerprint_hint": "Off uses Basic Mode; on enters Variation Mode on next start, enabling debug port and navigator injection",
            "settings.fingerprint_locked": "Close this environment before changing the mode",
            "settings.fingerprint_summary": "Enabled %d / %d environments",
            "settings.fingerprint_manage": "Manage Variation Mode",
            "settings.fingerprint_manage_title": "Manage Variation Mode",
            "settings.fingerprint_manage_description": "Variation Mode enables a debug port and injects hardwareConcurrency/deviceMemory on the next launch. Running environments must be closed before they can be changed.",
            "settings.fingerprint_search_placeholder": "Search environments",
            "settings.fingerprint_editable_only": "Show editable environments only",
            "settings.fingerprint_empty_profiles": "No environments yet",
            "settings.fingerprint_no_results": "No matching environments",
            "settings.fingerprint_no_editable": "No editable environments right now",
            "settings.fingerprint_locked_starting": "Starting; close before editing",
            "settings.fingerprint_locked_running": "Running; close before editing",
            "settings.fingerprint_locked_stopping": "Closing; editable after it stops",
            "settings.fingerprint_editable_status": "Editable, currently %@",
            "settings.basic_mode": "Basic Mode",
            "settings.variation_mode": "Variation Mode",
            "settings.appearance": "Appearance",
            "settings.appearance_system": "System",
            "settings.appearance_light": "Light",
            "settings.appearance_dark": "Dark",
            "settings.about_support": "About & Support",
            "settings.version_group": "Version & Updates",
            "settings.author_group": "Author",
            "settings.feedback_group": "Feedback",
            "settings.app_version": "Current Version",
            "settings.view_releases": "View Releases",
            "settings.author": "Author",
            "settings.email": "Email",
            "settings.open_issues": "Open Issues",
            "settings.copy_email": "Copy Email",
            "external_link.title": "Cannot Open Link Yet",
            "external_link.message": "The browser environment is not ready. Try again later or copy this link:\n%@",
            "external_link.no_profile_message": "No environment is available yet. Create or choose one first, then retry this link:\n%@",
            "external_link.copy": "Copy Link",
            "inspector.empty_title": "Select an Environment",
            "inspector.empty_subtitle": "Details will appear here",
            "inspector.basic": "Basic Info",
            "inspector.advanced": "Advanced Info",
            "inspector.actions": "Actions",
            "inspector.error": "Error",
            "inspector.retry": "Retry",
            "inspector.clear_error": "Clear",
            "inspector.open_profile_folder": "Open Profile Folder",
            "inspector.copy_profile_path": "Copy Profile Path",
            "inspector.last_used": "Last Used",
            "update.title": "Check for Updates",
            "update.up_to_date": "You are already on the latest version",
            "update.available_title": "New Version Available",
            "update.available_message": "Latest: %@\nCurrent: %@",
            "update.download": "Open Releases",
            "update.failed": "Could not connect to the server. Check your network and try again.",
            "quit.title": "Confirm Quit",
            "quit.confirm": "Close and Quit",
            "quit.message": "%d environments are still running. Quitting will close them all.",
            "download.title": "Downloading browser for first use",
            "download.preparing": "Preparing...",
            "download.progress": "Downloading... (about 237 MB)",
            "download.installing": "Installing...",
            "download.verifying": "Verifying...",
            "download.failed": "Download failed",
            "download.manual_title": "You can also install the browser manually:",
            "download.manual_steps": "1. Download Chrome: https://www.google.com/chrome/\n2. Open the DMG and move \"Google Chrome.app\"\n   into the target folder below",
            "download.open_folder": "Open Target Folder",
            "download.copy_error": "Copy Error",
            "download.use_existing": "Use Existing Chrome",
            "download.retry": "Retry Download"
        ],
        .ja: [
            "app.name": "ブラウザ分離",
            "common.cancel": "キャンセル",
            "common.confirm": "OK",
            "common.delete": "削除",
            "common.close": "閉じる",
            "common.start": "起動",
            "common.later": "後で",
            "language": "言語",
            "profile.default_name": "環境%d",
            "profile.display_name": "環境%d - %@",
            "empty.title": "環境はまだありません",
            "empty.subtitle": "ツールバーの + で追加",
            "toolbar.add": "環境を追加",
            "toolbar.stop_all": "すべて閉じる",
            "context.rename": "名前を変更",
            "context.delete": "削除",
            "delete.title": "削除の確認",
            "delete.message": "「%@」のデータをゴミ箱へ移動します。\n現在のデータサイズ：%@\n確認するには %@ と入力してください。",
            "delete.confirm_placeholder": "Delete",
            "status.starting": "起動中",
            "status.stopping": "終了中",
            "status.running": "実行中",
            "status.stopped": "停止中",
            "error.start_failed": "起動に失敗しました",
            "error.delete_failed": "削除に失敗しました",
            "error.profile_message": "%@\n%@",
            "config_save.title": "設定の保存に失敗しました",
            "config_load.title": "設定ファイルが壊れています",
            "config_load.message": "設定ファイルを読み込めなかったため、既定の設定を復元しました。",
            "config_load.message_with_backup": "設定ファイルを読み込めなかったため、壊れた副本を次に保存しました:\n%@",
            "meta.port": "ポート %d",
            "details.folder": "フォルダ",
            "details.profile_path": "データパス",
            "details.run_mode": "実行モード",
            "details.port": "デバッグポート",
            "details.cpu": "CPU コア",
            "details.memory": "メモリ",
            "date.today": "今日",
            "date.yesterday": "昨日",
            "date.days_ago": "%d日前",
            "date.month_day": "%d月%d日",
            "rename.title": "名前を変更",
            "rename.hint": "識別しやすい名前を付けます",
            "rename.placeholder": "この環境の名前",
            "context.note": "メモ",
            "note.hint": "プレーンテキストのみ、最大 120 文字",
            "note.placeholder": "メモを入力",
            "menu.open_panel": "管理パネルを開く",
            "menu.check_updates": "アップデートを確認",
            "menu.close_all_quit": "すべて閉じて終了",
            "menu.quit": "終了",
            "settings.title": "設定",
            "settings.browser": "ブラウザ",
            "settings.chrome_status": "Chrome 状態",
            "settings.ready": "利用可能",
            "settings.not_installed": "未インストール",
            "settings.chrome_version": "Chrome バージョン",
            "settings.unknown": "不明",
            "settings.open_chrome_folder": "インストール先",
            "settings.redownload_chrome": "再ダウンロード",
            "settings.redownload_confirm_title": "Chrome を再ダウンロードしますか？",
            "settings.redownload_confirm_message": "BrowserIsolator が使用する Chrome を再ダウンロードしてインストールします。ダウンロード中はブラウザ環境を使用できません。",
            "settings.data": "データ",
            "settings.data_path": "データフォルダ",
            "settings.open_data_folder": "データの場所を開く",
            "settings.open_profiles_folder": "環境フォルダを開く",
            "settings.copy_path": "パスをコピー",
            "settings.preferences": "環境設定",
            "settings.show_advanced": "詳細情報を表示",
            "settings.external_links": "外部リンク",
            "settings.open_to": "開き先",
            "settings.set_default_browser": "既定ブラウザに設定",
            "settings.fingerprint_mode": "差分モード",
            "settings.fingerprint_profiles": "環境",
            "settings.fingerprint_hint": "オフでは基本モード。オンにすると次回起動時に差分モードになり、デバッグポートと navigator 注入を有効化します",
            "settings.fingerprint_locked": "実行中の環境は閉じてから変更してください",
            "settings.fingerprint_summary": "%d / %d 個の環境で有効",
            "settings.fingerprint_manage": "差分モードを管理",
            "settings.fingerprint_manage_title": "差分モードを管理",
            "settings.fingerprint_manage_description": "差分モードは次回起動時にデバッグポートを有効にし、hardwareConcurrency/deviceMemory を注入します。実行中の環境は閉じてから変更してください。",
            "settings.fingerprint_search_placeholder": "環境を検索",
            "settings.fingerprint_editable_only": "編集可能な環境のみ表示",
            "settings.fingerprint_empty_profiles": "環境がありません",
            "settings.fingerprint_no_results": "一致する環境がありません",
            "settings.fingerprint_no_editable": "現在編集可能な環境はありません",
            "settings.fingerprint_locked_starting": "起動中です。閉じてから変更できます",
            "settings.fingerprint_locked_running": "実行中です。閉じてから変更できます",
            "settings.fingerprint_locked_stopping": "終了中です。停止後に変更できます",
            "settings.fingerprint_editable_status": "変更可能、現在は%@",
            "settings.basic_mode": "基本モード",
            "settings.variation_mode": "差分モード",
            "settings.about_support": "情報とサポート",
            "settings.version_group": "バージョンと更新",
            "settings.author_group": "作者",
            "settings.feedback_group": "フィードバック",
            "settings.app_version": "現在のバージョン",
            "settings.view_releases": "リリースを開く",
            "settings.author": "作者",
            "settings.email": "メール",
            "settings.open_issues": "Issues を開く",
            "settings.copy_email": "メールをコピー",
            "external_link.title": "リンクをまだ開けません",
            "external_link.message": "ブラウザ環境の準備ができていません。あとでもう一度試すか、このリンクをコピーしてください：\n%@",
            "external_link.no_profile_message": "利用できる環境がありません。先に環境を作成または選択してから、このリンクを再試行してください：\n%@",
            "external_link.copy": "リンクをコピー",
            "inspector.empty_title": "環境を選択",
            "inspector.empty_subtitle": "ここに詳細が表示されます",
            "inspector.basic": "基本情報",
            "inspector.advanced": "詳細情報",
            "inspector.actions": "操作",
            "inspector.error": "エラー",
            "inspector.retry": "再試行",
            "inspector.clear_error": "クリア",
            "inspector.open_profile_folder": "この環境フォルダを開く",
            "inspector.copy_profile_path": "環境パスをコピー",
            "inspector.last_used": "最終使用",
            "update.title": "アップデート確認",
            "update.up_to_date": "現在のバージョンは最新です",
            "update.available_title": "新しいバージョンがあります",
            "update.available_message": "最新: %@\n現在: %@",
            "update.download": "リリースページへ",
            "update.failed": "サーバーに接続できません。ネットワークを確認してください。",
            "quit.title": "終了の確認",
            "quit.confirm": "閉じて終了",
            "quit.message": "%d 個の環境が実行中です。終了するとすべて閉じます。",
            "download.title": "初回使用のためブラウザをダウンロード中",
            "download.preparing": "準備中...",
            "download.progress": "ダウンロード中...（約 237 MB）",
            "download.installing": "インストール中...",
            "download.verifying": "検証中...",
            "download.failed": "ダウンロード失敗",
            "download.manual_title": "手動でブラウザをインストールすることもできます：",
            "download.manual_steps": "1. Chrome をダウンロード：https://www.google.com/chrome/\n2. DMG を開き、「Google Chrome.app」を\n   下の対象フォルダへ移動",
            "download.open_folder": "対象フォルダを開く",
            "download.copy_error": "エラーをコピー",
            "download.use_existing": "現在の Chrome を使用",
            "download.retry": "再試行"
        ],
    ]
}
