import Foundation

enum AppLanguage: String, CaseIterable, Identifiable {
    case zh
    case en
    case ja
    case ko
    case de
    case fr
    case ru

    var id: String { rawValue }

    var nativeName: String {
        switch self {
        case .zh: return "中文"
        case .en: return "English"
        case .ja: return "日本語"
        case .ko: return "한국어"
        case .de: return "Deutsch"
        case .fr: return "Français"
        case .ru: return "Русский"
        }
    }

    var localeIdentifier: String {
        switch self {
        case .zh: return "zh_Hans"
        case .en: return "en"
        case .ja: return "ja"
        case .ko: return "ko"
        case .de: return "de"
        case .fr: return "fr"
        case .ru: return "ru"
        }
    }

    static var preferred: AppLanguage {
        let codes = Locale.preferredLanguages.map { Locale(identifier: $0).language.languageCode?.identifier ?? $0 }
        for code in codes {
            if code.hasPrefix("zh") { return .zh }
            if code.hasPrefix("en") { return .en }
            if code.hasPrefix("ja") { return .ja }
            if code.hasPrefix("ko") { return .ko }
            if code.hasPrefix("de") { return .de }
            if code.hasPrefix("fr") { return .fr }
            if code.hasPrefix("ru") { return .ru }
        }
        return .zh
    }
}

@MainActor
final class Localization: ObservableObject {
    @Published var language: AppLanguage {
        didSet {
            UserDefaults.standard.set(language.rawValue, forKey: Self.storageKey)
        }
    }

    private static let storageKey = "AppLanguage"

    init() {
        if let raw = UserDefaults.standard.string(forKey: Self.storageKey),
           let saved = AppLanguage(rawValue: raw) {
            self.language = saved
        } else {
            self.language = .preferred
        }
    }

    var locale: Locale {
        Locale(identifier: language.localeIdentifier)
    }

    func t(_ key: String) -> String {
        Self.translations[language]?[key] ?? Self.translations[.en]?[key] ?? key
    }

    func format(_ key: String, _ args: CVarArg...) -> String {
        String(format: t(key), locale: locale, arguments: args)
    }

    private static let translations: [AppLanguage: [String: String]] = [
        .zh: [
            "app.name": "浏览器多开",
            "common.cancel": "取消",
            "common.confirm": "确定",
            "common.delete": "删除",
            "common.close": "关闭",
            "common.start": "启动",
            "common.later": "稍后",
            "language": "语言",
            "profile.default_name": "环境%d",
            "profile.display_name": "环境%d - %@",
            "empty.title": "还没有环境",
            "empty.subtitle": "点击工具栏 + 添加一个",
            "toolbar.add": "添加环境",
            "toolbar.stop_all": "全部关闭",
            "context.rename": "重命名",
            "context.delete": "删除",
            "delete.title": "确认删除",
            "delete.message": "将把「%@」的数据移到废纸篓。\n当前数据大小：%@\n请输入环境名称确认。",
            "delete.confirm_placeholder": "输入环境名称",
            "status.starting": "启动中",
            "status.stopping": "关闭中",
            "status.running": "运行中",
            "status.stopped": "未启动",
            "error.start_failed": "启动失败",
            "error.delete_failed": "删除失败",
            "error.profile_message": "%@\n%@",
            "config_save.title": "配置保存失败",
            "config_load.title": "配置文件已损坏",
            "config_load.message": "配置文件读取失败，已恢复默认配置。",
            "config_load.message_with_backup": "配置文件读取失败，损坏副本已保存在：\n%@",
            "meta.port": "端口 %d",
            "details.folder": "环境目录",
            "details.profile_path": "数据路径",
            "details.run_mode": "运行模式",
            "details.port": "调试端口",
            "details.cpu": "CPU 核心",
            "details.memory": "内存",
            "date.today": "今天",
            "date.yesterday": "昨天",
            "date.days_ago": "%d天前",
            "date.month_day": "%d月%d日",
            "rename.title": "重命名",
            "rename.hint": "自定义名称，方便识别",
            "rename.placeholder": "为此环境命名",
            "context.note": "备注",
            "note.hint": "纯文本备注，最多 120 个 Unicode 字符",
            "note.placeholder": "输入备注",
            "menu.open_panel": "打开管理面板",
            "menu.check_updates": "检查更新",
            "menu.close_all_quit": "全部关闭并退出",
            "menu.quit": "退出",
            "settings.title": "设置",
            "settings.browser": "浏览器",
            "settings.chrome_status": "Chrome 状态",
            "settings.ready": "可用",
            "settings.not_installed": "未安装",
            "settings.chrome_version": "Chrome 版本",
            "settings.unknown": "未知",
            "settings.open_chrome_folder": "打开 Chrome 文件夹",
            "settings.redownload_chrome": "重新下载 Chrome",
            "settings.data": "数据",
            "settings.data_path": "数据目录",
            "settings.open_data_folder": "打开数据目录",
            "settings.open_profiles_folder": "打开环境目录",
            "settings.copy_path": "复制路径",
            "settings.preferences": "偏好",
            "settings.show_advanced": "显示高级详情",
            "settings.external_links": "外部链接",
            "settings.open_to": "打开到",
            "settings.set_default_browser": "设为默认浏览器",
            "settings.fingerprint_mode": "差异模式",
            "settings.fingerprint_profiles": "环境",
            "settings.fingerprint_hint": "关闭时使用基础模式；开启后下次启动进入差异模式，启用调试端口和 navigator 注入",
            "settings.fingerprint_locked": "运行中的环境需要关闭后再切换",
            "settings.basic_mode": "基础模式",
            "settings.variation_mode": "差异模式",
            "settings.appearance": "外观",
            "settings.appearance_system": "跟随系统",
            "settings.appearance_light": "浅色",
            "settings.appearance_dark": "深色",
            "settings.about_support": "关于与支持",
            "settings.version_group": "版本与更新",
            "settings.author_group": "作者",
            "settings.feedback_group": "反馈",
            "settings.app_version": "当前版本",
            "settings.view_releases": "查看发布页",
            "settings.author": "作者",
            "settings.email": "邮箱",
            "settings.open_issues": "查看 Issues",
            "settings.copy_email": "复制邮箱",
            "external_link.title": "暂时无法打开链接",
            "external_link.message": "浏览器环境还没准备好。你可以稍后重试，或先复制这个链接：\n%@",
            "external_link.no_profile_message": "当前没有可用环境。请先创建或选择一个环境，再重试这个链接：\n%@",
            "external_link.copy": "复制链接",
            "inspector.empty_title": "选择一个环境",
            "inspector.empty_subtitle": "详情会显示在这里",
            "inspector.basic": "基础信息",
            "inspector.advanced": "高级信息",
            "inspector.actions": "操作",
            "inspector.error": "错误",
            "inspector.retry": "重试",
            "inspector.clear_error": "清除",
            "inspector.open_profile_folder": "打开此环境目录",
            "inspector.copy_profile_path": "复制环境路径",
            "inspector.last_used": "最近使用",
            "update.title": "检查更新",
            "update.up_to_date": "当前已是最新版本",
            "update.available_title": "发现新版本",
            "update.available_message": "最新版本: %@\n当前版本: %@",
            "update.download": "前往发布页",
            "update.failed": "无法连接服务器，请检查网络后重试",
            "quit.title": "确认退出",
            "quit.confirm": "关闭并退出",
            "quit.message": "还有 %d 个环境正在运行，退出将自动关闭所有环境。",
            "download.title": "首次使用，正在下载浏览器",
            "download.preparing": "准备中...",
            "download.progress": "下载中...（约 237MB）",
            "download.installing": "正在安装...",
            "download.verifying": "正在校验...",
            "download.failed": "下载失败",
            "download.manual_title": "你也可以手动安装浏览器：",
            "download.manual_steps": "1. 下载 Chrome：https://www.google.com/chrome/\n2. 双击 dmg，将「Google Chrome.app」\n   拖入下方目标文件夹",
            "download.open_folder": "打开目标文件夹",
            "download.copy_error": "复制错误",
            "download.use_existing": "继续使用当前 Chrome",
            "download.retry": "重试下载"
        ],
        .en: [
            "app.name": "Browser Isolator",
            "common.cancel": "Cancel",
            "common.confirm": "OK",
            "common.delete": "Delete",
            "common.close": "Close",
            "common.start": "Start",
            "common.later": "Later",
            "language": "Language",
            "profile.default_name": "Environment %d",
            "profile.display_name": "Environment %d - %@",
            "empty.title": "No environments yet",
            "empty.subtitle": "Click + in the toolbar to add one",
            "toolbar.add": "Add Environment",
            "toolbar.stop_all": "Close All",
            "context.rename": "Rename",
            "context.delete": "Delete",
            "delete.title": "Confirm Delete",
            "delete.message": "Move data for \"%@\" to Trash.\nCurrent data size: %@\nType the environment name to confirm.",
            "delete.confirm_placeholder": "Type environment name",
            "status.starting": "Starting",
            "status.stopping": "Closing",
            "status.running": "Running",
            "status.stopped": "Stopped",
            "error.start_failed": "Start Failed",
            "error.delete_failed": "Delete Failed",
            "error.profile_message": "%@\n%@",
            "config_save.title": "Save Failed",
            "config_load.title": "Config File Corrupted",
            "config_load.message": "The config file could not be read. A clean default configuration was loaded.",
            "config_load.message_with_backup": "The config file could not be read. The corrupted copy was saved to:\n%@",
            "meta.port": "Port %d",
            "details.folder": "Folder",
            "details.profile_path": "Data path",
            "details.run_mode": "Run mode",
            "details.port": "Debug port",
            "details.cpu": "CPU cores",
            "details.memory": "Memory",
            "date.today": "Today",
            "date.yesterday": "Yesterday",
            "date.days_ago": "%d days ago",
            "date.month_day": "%d/%d",
            "rename.title": "Rename",
            "rename.hint": "Add a custom name for recognition",
            "rename.placeholder": "Name this environment",
            "context.note": "Note",
            "note.hint": "Plain text only, up to 120 Unicode characters",
            "note.placeholder": "Enter a note",
            "menu.open_panel": "Open Panel",
            "menu.check_updates": "Check for Updates",
            "menu.close_all_quit": "Close All and Quit",
            "menu.quit": "Quit",
            "settings.title": "Settings",
            "settings.browser": "Browser",
            "settings.chrome_status": "Chrome Status",
            "settings.ready": "Ready",
            "settings.not_installed": "Not Installed",
            "settings.chrome_version": "Chrome Version",
            "settings.unknown": "Unknown",
            "settings.open_chrome_folder": "Open Chrome Folder",
            "settings.redownload_chrome": "Redownload Chrome",
            "settings.data": "Data",
            "settings.data_path": "Data Folder",
            "settings.open_data_folder": "Open Data Folder",
            "settings.open_profiles_folder": "Open Profiles Folder",
            "settings.copy_path": "Copy Path",
            "settings.preferences": "Preferences",
            "settings.show_advanced": "Show advanced details",
            "settings.external_links": "External Links",
            "settings.open_to": "Open in",
            "settings.set_default_browser": "Set as Default Browser",
            "settings.fingerprint_mode": "Variation Mode",
            "settings.fingerprint_profiles": "Environments",
            "settings.fingerprint_hint": "Off uses Basic Mode; on enters Variation Mode on next start, enabling debug port and navigator injection",
            "settings.fingerprint_locked": "Close this environment before changing the mode",
            "settings.basic_mode": "Basic Mode",
            "settings.variation_mode": "Variation Mode",
            "settings.appearance": "Appearance",
            "settings.appearance_system": "System",
            "settings.appearance_light": "Light",
            "settings.appearance_dark": "Dark",
            "settings.about_support": "About & Support",
            "settings.version_group": "Version & Updates",
            "settings.author_group": "Author",
            "settings.feedback_group": "Feedback",
            "settings.app_version": "Current Version",
            "settings.view_releases": "View Releases",
            "settings.author": "Author",
            "settings.email": "Email",
            "settings.open_issues": "Open Issues",
            "settings.copy_email": "Copy Email",
            "external_link.title": "Cannot Open Link Yet",
            "external_link.message": "The browser environment is not ready. Try again later or copy this link:\n%@",
            "external_link.no_profile_message": "No environment is available yet. Create or choose one first, then retry this link:\n%@",
            "external_link.copy": "Copy Link",
            "inspector.empty_title": "Select an Environment",
            "inspector.empty_subtitle": "Details will appear here",
            "inspector.basic": "Basic Info",
            "inspector.advanced": "Advanced Info",
            "inspector.actions": "Actions",
            "inspector.error": "Error",
            "inspector.retry": "Retry",
            "inspector.clear_error": "Clear",
            "inspector.open_profile_folder": "Open Profile Folder",
            "inspector.copy_profile_path": "Copy Profile Path",
            "inspector.last_used": "Last Used",
            "update.title": "Check for Updates",
            "update.up_to_date": "You are already on the latest version",
            "update.available_title": "New Version Available",
            "update.available_message": "Latest: %@\nCurrent: %@",
            "update.download": "Open Releases",
            "update.failed": "Could not connect to the server. Check your network and try again.",
            "quit.title": "Confirm Quit",
            "quit.confirm": "Close and Quit",
            "quit.message": "%d environments are still running. Quitting will close them all.",
            "download.title": "Downloading browser for first use",
            "download.preparing": "Preparing...",
            "download.progress": "Downloading... (about 237 MB)",
            "download.installing": "Installing...",
            "download.verifying": "Verifying...",
            "download.failed": "Download failed",
            "download.manual_title": "You can also install the browser manually:",
            "download.manual_steps": "1. Download Chrome: https://www.google.com/chrome/\n2. Open the DMG and move \"Google Chrome.app\"\n   into the target folder below",
            "download.open_folder": "Open Target Folder",
            "download.copy_error": "Copy Error",
            "download.use_existing": "Use Existing Chrome",
            "download.retry": "Retry Download"
        ],
        .ja: [
            "app.name": "ブラウザ分離",
            "common.cancel": "キャンセル",
            "common.confirm": "OK",
            "common.delete": "削除",
            "common.close": "閉じる",
            "common.start": "起動",
            "common.later": "後で",
            "language": "言語",
            "profile.default_name": "環境%d",
            "profile.display_name": "環境%d - %@",
            "empty.title": "環境はまだありません",
            "empty.subtitle": "ツールバーの + で追加",
            "toolbar.add": "環境を追加",
            "toolbar.stop_all": "すべて閉じる",
            "context.rename": "名前を変更",
            "context.delete": "削除",
            "delete.title": "削除の確認",
            "delete.message": "「%@」のデータをゴミ箱へ移動します。\n現在のデータサイズ：%@\n環境名を入力して確認してください。",
            "delete.confirm_placeholder": "環境名を入力",
            "status.starting": "起動中",
            "status.stopping": "終了中",
            "status.running": "実行中",
            "status.stopped": "停止中",
            "error.start_failed": "起動に失敗しました",
            "error.delete_failed": "削除に失敗しました",
            "error.profile_message": "%@\n%@",
            "config_save.title": "設定の保存に失敗しました",
            "config_load.title": "設定ファイルが壊れています",
            "config_load.message": "設定ファイルを読み込めなかったため、既定の設定を復元しました。",
            "config_load.message_with_backup": "設定ファイルを読み込めなかったため、壊れた副本を次に保存しました:\n%@",
            "meta.port": "ポート %d",
            "details.folder": "フォルダ",
            "details.profile_path": "データパス",
            "details.run_mode": "実行モード",
            "details.port": "デバッグポート",
            "details.cpu": "CPU コア",
            "details.memory": "メモリ",
            "date.today": "今日",
            "date.yesterday": "昨日",
            "date.days_ago": "%d日前",
            "date.month_day": "%d月%d日",
            "rename.title": "名前を変更",
            "rename.hint": "識別しやすい名前を付けます",
            "rename.placeholder": "この環境の名前",
            "context.note": "メモ",
            "note.hint": "プレーンテキストのみ、最大 120 文字",
            "note.placeholder": "メモを入力",
            "menu.open_panel": "管理パネルを開く",
            "menu.check_updates": "アップデートを確認",
            "menu.close_all_quit": "すべて閉じて終了",
            "menu.quit": "終了",
            "settings.title": "設定",
            "settings.browser": "ブラウザ",
            "settings.chrome_status": "Chrome 状態",
            "settings.ready": "利用可能",
            "settings.not_installed": "未インストール",
            "settings.chrome_version": "Chrome バージョン",
            "settings.unknown": "不明",
            "settings.open_chrome_folder": "Chrome フォルダを開く",
            "settings.redownload_chrome": "Chrome を再ダウンロード",
            "settings.data": "データ",
            "settings.data_path": "データフォルダ",
            "settings.open_data_folder": "データフォルダを開く",
            "settings.open_profiles_folder": "環境フォルダを開く",
            "settings.copy_path": "パスをコピー",
            "settings.preferences": "環境設定",
            "settings.show_advanced": "詳細情報を表示",
            "settings.external_links": "外部リンク",
            "settings.open_to": "開き先",
            "settings.set_default_browser": "既定のブラウザにする",
            "settings.fingerprint_mode": "差分モード",
            "settings.fingerprint_profiles": "環境",
            "settings.fingerprint_hint": "オフでは基本モード。オンにすると次回起動時に差分モードになり、デバッグポートと navigator 注入を有効化します",
            "settings.fingerprint_locked": "実行中の環境は閉じてから変更してください",
            "settings.basic_mode": "基本モード",
            "settings.variation_mode": "差分モード",
            "settings.about_support": "情報とサポート",
            "settings.version_group": "バージョンと更新",
            "settings.author_group": "作者",
            "settings.feedback_group": "フィードバック",
            "settings.app_version": "現在のバージョン",
            "settings.view_releases": "リリースを開く",
            "settings.author": "作者",
            "settings.email": "メール",
            "settings.open_issues": "Issues を開く",
            "settings.copy_email": "メールをコピー",
            "external_link.title": "リンクをまだ開けません",
            "external_link.message": "ブラウザ環境の準備ができていません。あとでもう一度試すか、このリンクをコピーしてください：\n%@",
            "external_link.no_profile_message": "利用できる環境がありません。先に環境を作成または選択してから、このリンクを再試行してください：\n%@",
            "external_link.copy": "リンクをコピー",
            "inspector.empty_title": "環境を選択",
            "inspector.empty_subtitle": "ここに詳細が表示されます",
            "inspector.basic": "基本情報",
            "inspector.advanced": "詳細情報",
            "inspector.actions": "操作",
            "inspector.error": "エラー",
            "inspector.retry": "再試行",
            "inspector.clear_error": "クリア",
            "inspector.open_profile_folder": "この環境フォルダを開く",
            "inspector.copy_profile_path": "環境パスをコピー",
            "inspector.last_used": "最終使用",
            "update.title": "アップデート確認",
            "update.up_to_date": "現在のバージョンは最新です",
            "update.available_title": "新しいバージョンがあります",
            "update.available_message": "最新: %@\n現在: %@",
            "update.download": "リリースページへ",
            "update.failed": "サーバーに接続できません。ネットワークを確認してください。",
            "quit.title": "終了の確認",
            "quit.confirm": "閉じて終了",
            "quit.message": "%d 個の環境が実行中です。終了するとすべて閉じます。",
            "download.title": "初回使用のためブラウザをダウンロード中",
            "download.preparing": "準備中...",
            "download.progress": "ダウンロード中...（約 237 MB）",
            "download.installing": "インストール中...",
            "download.verifying": "検証中...",
            "download.failed": "ダウンロード失敗",
            "download.manual_title": "手動でブラウザをインストールすることもできます：",
            "download.manual_steps": "1. Chrome をダウンロード：https://www.google.com/chrome/\n2. DMG を開き、「Google Chrome.app」を\n   下の対象フォルダへ移動",
            "download.open_folder": "対象フォルダを開く",
            "download.copy_error": "エラーをコピー",
            "download.use_existing": "現在の Chrome を使用",
            "download.retry": "再試行"
        ],
        .ko: [
            "app.name": "브라우저 분리",
            "common.cancel": "취소",
            "common.confirm": "확인",
            "common.delete": "삭제",
            "common.close": "닫기",
            "common.start": "시작",
            "common.later": "나중에",
            "language": "언어",
            "profile.default_name": "환경 %d",
            "profile.display_name": "환경 %d - %@",
            "empty.title": "아직 환경이 없습니다",
            "empty.subtitle": "툴바의 + 버튼으로 추가하세요",
            "toolbar.add": "환경 추가",
            "toolbar.stop_all": "모두 닫기",
            "context.rename": "이름 변경",
            "context.delete": "삭제",
            "delete.title": "삭제 확인",
            "delete.message": "\"%@\" 데이터를 휴지통으로 이동합니다.\n현재 데이터 크기: %@\n환경 이름을 입력해 확인하세요.",
            "delete.confirm_placeholder": "환경 이름 입력",
            "status.starting": "시작 중",
            "status.stopping": "닫는 중",
            "status.running": "실행 중",
            "status.stopped": "중지됨",
            "error.start_failed": "시작 실패",
            "error.delete_failed": "삭제 실패",
            "error.profile_message": "%@\n%@",
            "config_save.title": "저장 실패",
            "config_load.title": "설정 파일이 손상되었습니다",
            "config_load.message": "설정 파일을 읽지 못해 기본 설정을 복원했습니다.",
            "config_load.message_with_backup": "설정 파일을 읽지 못해 손상된 사본을 다음 위치에 저장했습니다:\n%@",
            "meta.port": "포트 %d",
            "details.folder": "폴더",
            "details.profile_path": "데이터 경로",
            "details.run_mode": "실행 모드",
            "details.port": "디버그 포트",
            "details.cpu": "CPU 코어",
            "details.memory": "메모리",
            "date.today": "오늘",
            "date.yesterday": "어제",
            "date.days_ago": "%d일 전",
            "date.month_day": "%d월 %d일",
            "rename.title": "이름 변경",
            "rename.hint": "구분하기 쉬운 이름을 추가하세요",
            "rename.placeholder": "이 환경 이름",
            "context.note": "메모",
            "note.hint": "일반 텍스트만, 최대 120자",
            "note.placeholder": "메모 입력",
            "menu.open_panel": "관리 패널 열기",
            "menu.check_updates": "업데이트 확인",
            "menu.close_all_quit": "모두 닫고 종료",
            "menu.quit": "종료",
            "settings.title": "설정",
            "settings.browser": "브라우저",
            "settings.chrome_status": "Chrome 상태",
            "settings.ready": "사용 가능",
            "settings.not_installed": "설치되지 않음",
            "settings.chrome_version": "Chrome 버전",
            "settings.unknown": "알 수 없음",
            "settings.open_chrome_folder": "Chrome 폴더 열기",
            "settings.redownload_chrome": "Chrome 다시 다운로드",
            "settings.data": "데이터",
            "settings.data_path": "데이터 폴더",
            "settings.open_data_folder": "데이터 폴더 열기",
            "settings.open_profiles_folder": "환경 폴더 열기",
            "settings.copy_path": "경로 복사",
            "settings.preferences": "환경설정",
            "settings.show_advanced": "고급 세부 정보 표시",
            "settings.external_links": "외부 링크",
            "settings.open_to": "열기 위치",
            "settings.set_default_browser": "기본 브라우저로 지정",
            "settings.fingerprint_mode": "차이 모드",
            "settings.fingerprint_profiles": "환경",
            "settings.fingerprint_hint": "끄면 기본 모드입니다. 켜면 다음 시작 때 차이 모드로 실행되어 디버그 포트와 navigator 주입을 사용합니다",
            "settings.fingerprint_locked": "실행 중인 환경은 닫은 뒤 변경하세요",
            "settings.basic_mode": "기본 모드",
            "settings.variation_mode": "차이 모드",
            "settings.about_support": "정보 및 지원",
            "settings.version_group": "버전 및 업데이트",
            "settings.author_group": "작성자",
            "settings.feedback_group": "피드백",
            "settings.app_version": "현재 버전",
            "settings.view_releases": "릴리스 보기",
            "settings.author": "작성자",
            "settings.email": "이메일",
            "settings.open_issues": "이슈 열기",
            "settings.copy_email": "이메일 복사",
            "external_link.title": "아직 링크를 열 수 없습니다",
            "external_link.message": "브라우저 환경이 아직 준비되지 않았습니다. 나중에 다시 시도하거나 이 링크를 복사하세요:\n%@",
            "external_link.no_profile_message": "아직 사용할 수 있는 환경이 없습니다. 먼저 환경을 만들거나 선택한 다음 이 링크를 다시 시도하세요:\n%@",
            "external_link.copy": "링크 복사",
            "inspector.empty_title": "환경 선택",
            "inspector.empty_subtitle": "여기에 세부 정보가 표시됩니다",
            "inspector.basic": "기본 정보",
            "inspector.advanced": "고급 정보",
            "inspector.actions": "작업",
            "inspector.error": "오류",
            "inspector.retry": "다시 시도",
            "inspector.clear_error": "지우기",
            "inspector.open_profile_folder": "이 환경 폴더 열기",
            "inspector.copy_profile_path": "환경 경로 복사",
            "inspector.last_used": "마지막 사용",
            "update.title": "업데이트 확인",
            "update.up_to_date": "이미 최신 버전입니다",
            "update.available_title": "새 버전 발견",
            "update.available_message": "최신: %@\n현재: %@",
            "update.download": "릴리스 페이지로 이동",
            "update.failed": "서버에 연결할 수 없습니다. 네트워크를 확인하세요.",
            "quit.title": "종료 확인",
            "quit.confirm": "닫고 종료",
            "quit.message": "%d개의 환경이 실행 중입니다. 종료하면 모두 닫힙니다.",
            "download.title": "처음 사용을 위해 브라우저 다운로드 중",
            "download.preparing": "준비 중...",
            "download.progress": "다운로드 중... (약 237 MB)",
            "download.installing": "설치 중...",
            "download.verifying": "확인 중...",
            "download.failed": "다운로드 실패",
            "download.manual_title": "브라우저를 수동으로 설치할 수도 있습니다:",
            "download.manual_steps": "1. Chrome 다운로드: https://www.google.com/chrome/\n2. DMG를 열고 \"Google Chrome.app\"을\n   아래 대상 폴더로 이동",
            "download.open_folder": "대상 폴더 열기",
            "download.copy_error": "오류 복사",
            "download.use_existing": "현재 Chrome 사용",
            "download.retry": "다시 다운로드"
        ],
        .de: [
            "app.name": "Browser-Isolator",
            "common.cancel": "Abbrechen",
            "common.confirm": "OK",
            "common.delete": "Löschen",
            "common.close": "Schließen",
            "common.start": "Starten",
            "common.later": "Später",
            "language": "Sprache",
            "profile.default_name": "Umgebung %d",
            "profile.display_name": "Umgebung %d - %@",
            "empty.title": "Noch keine Umgebungen",
            "empty.subtitle": "Klicke auf + in der Symbolleiste",
            "toolbar.add": "Umgebung hinzufügen",
            "toolbar.stop_all": "Alle schließen",
            "context.rename": "Umbenennen",
            "context.delete": "Löschen",
            "delete.title": "Löschen bestätigen",
            "delete.message": "Daten für „%@“ in den Papierkorb verschieben.\nAktuelle Datengröße: %@\nGib den Umgebungsnamen zur Bestätigung ein.",
            "delete.confirm_placeholder": "Umgebungsnamen eingeben",
            "status.starting": "Startet",
            "status.stopping": "Schließt",
            "status.running": "Läuft",
            "status.stopped": "Gestoppt",
            "error.start_failed": "Start fehlgeschlagen",
            "error.delete_failed": "Löschen fehlgeschlagen",
            "error.profile_message": "%@\n%@",
            "config_save.title": "Speichern fehlgeschlagen",
            "config_load.title": "Konfigurationsdatei beschädigt",
            "config_load.message": "Die Konfigurationsdatei konnte nicht gelesen werden. Eine saubere Standardkonfiguration wurde geladen.",
            "config_load.message_with_backup": "Die Konfigurationsdatei konnte nicht gelesen werden. Die beschädigte Kopie wurde gespeichert unter:\n%@",
            "meta.port": "Port %d",
            "details.folder": "Ordner",
            "details.profile_path": "Datenpfad",
            "details.run_mode": "Ausführungsmodus",
            "details.port": "Debug-Port",
            "details.cpu": "CPU-Kerne",
            "details.memory": "Speicher",
            "date.today": "Heute",
            "date.yesterday": "Gestern",
            "date.days_ago": "vor %d Tagen",
            "date.month_day": "%d.%d.",
            "rename.title": "Umbenennen",
            "rename.hint": "Eigener Name zur besseren Erkennung",
            "rename.placeholder": "Diese Umgebung benennen",
            "context.note": "Notiz",
            "note.hint": "Nur Klartext, bis zu 120 Unicode-Zeichen",
            "note.placeholder": "Notiz eingeben",
            "menu.open_panel": "Panel öffnen",
            "menu.check_updates": "Nach Updates suchen",
            "menu.close_all_quit": "Alle schließen und beenden",
            "menu.quit": "Beenden",
            "settings.title": "Einstellungen",
            "settings.browser": "Browser",
            "settings.chrome_status": "Chrome-Status",
            "settings.ready": "Bereit",
            "settings.not_installed": "Nicht installiert",
            "settings.chrome_version": "Chrome-Version",
            "settings.unknown": "Unbekannt",
            "settings.open_chrome_folder": "Chrome-Ordner öffnen",
            "settings.redownload_chrome": "Chrome erneut laden",
            "settings.data": "Daten",
            "settings.data_path": "Datenordner",
            "settings.open_data_folder": "Datenordner öffnen",
            "settings.open_profiles_folder": "Profilordner öffnen",
            "settings.copy_path": "Pfad kopieren",
            "settings.preferences": "Einstellungen",
            "settings.show_advanced": "Erweiterte Details anzeigen",
            "settings.external_links": "Externe Links",
            "settings.open_to": "Öffnen in",
            "settings.set_default_browser": "Als Standardbrowser setzen",
            "settings.fingerprint_mode": "Variationsmodus",
            "settings.fingerprint_profiles": "Umgebungen",
            "settings.fingerprint_hint": "Aus nutzt Basismodus; Ein startet beim nächsten Mal im Variationsmodus mit Debug-Port und navigator-Injektion",
            "settings.fingerprint_locked": "Schließen Sie diese Umgebung, bevor Sie den Modus ändern",
            "settings.basic_mode": "Basismodus",
            "settings.variation_mode": "Variationsmodus",
            "settings.about_support": "Info & Hilfe",
            "settings.version_group": "Version & Updates",
            "settings.author_group": "Autor",
            "settings.feedback_group": "Feedback",
            "settings.app_version": "Aktuelle Version",
            "settings.view_releases": "Release-Seite öffnen",
            "settings.author": "Autor",
            "settings.email": "E-Mail",
            "settings.open_issues": "Issues öffnen",
            "settings.copy_email": "E-Mail kopieren",
            "external_link.title": "Link noch nicht verfügbar",
            "external_link.message": "Die Browserumgebung ist noch nicht bereit. Versuche es später erneut oder kopiere diesen Link:\n%@",
            "external_link.no_profile_message": "Noch ist keine Umgebung verfügbar. Bitte erst eine Umgebung anlegen oder auswählen und dann diesen Link erneut versuchen:\n%@",
            "external_link.copy": "Link kopieren",
            "inspector.empty_title": "Umgebung auswählen",
            "inspector.empty_subtitle": "Details erscheinen hier",
            "inspector.basic": "Basisinfos",
            "inspector.advanced": "Erweiterte Infos",
            "inspector.actions": "Aktionen",
            "inspector.error": "Fehler",
            "inspector.retry": "Erneut versuchen",
            "inspector.clear_error": "Löschen",
            "inspector.open_profile_folder": "Diesen Profilordner öffnen",
            "inspector.copy_profile_path": "Profilpfad kopieren",
            "inspector.last_used": "Letzte Nutzung",
            "update.title": "Nach Updates suchen",
            "update.up_to_date": "Du verwendest bereits die neueste Version",
            "update.available_title": "Neue Version verfügbar",
            "update.available_message": "Neueste: %@\nAktuell: %@",
            "update.download": "Releases öffnen",
            "update.failed": "Keine Verbindung zum Server. Bitte Netzwerk prüfen.",
            "quit.title": "Beenden bestätigen",
            "quit.confirm": "Schließen und beenden",
            "quit.message": "%d Umgebungen laufen noch. Beim Beenden werden alle geschlossen.",
            "download.title": "Browser wird für die erste Nutzung geladen",
            "download.preparing": "Vorbereitung...",
            "download.progress": "Download läuft... (ca. 237 MB)",
            "download.installing": "Installation läuft...",
            "download.verifying": "Prüfung läuft...",
            "download.failed": "Download fehlgeschlagen",
            "download.manual_title": "Du kannst den Browser auch manuell installieren:",
            "download.manual_steps": "1. Chrome herunterladen: https://www.google.com/chrome/\n2. DMG öffnen und „Google Chrome.app“\n   in den Zielordner unten verschieben",
            "download.open_folder": "Zielordner öffnen",
            "download.copy_error": "Fehler kopieren",
            "download.use_existing": "Vorhandenes Chrome verwenden",
            "download.retry": "Erneut versuchen"
        ],
        .fr: [
            "app.name": "Isolateur de navigateur",
            "common.cancel": "Annuler",
            "common.confirm": "OK",
            "common.delete": "Supprimer",
            "common.close": "Fermer",
            "common.start": "Démarrer",
            "common.later": "Plus tard",
            "language": "Langue",
            "profile.default_name": "Environnement %d",
            "profile.display_name": "Environnement %d - %@",
            "empty.title": "Aucun environnement",
            "empty.subtitle": "Cliquez sur + dans la barre d'outils",
            "toolbar.add": "Ajouter un environnement",
            "toolbar.stop_all": "Tout fermer",
            "context.rename": "Renommer",
            "context.delete": "Supprimer",
            "delete.title": "Confirmer la suppression",
            "delete.message": "Déplacer les données de « %@ » vers la corbeille.\nTaille actuelle : %@\nSaisissez le nom de l'environnement pour confirmer.",
            "delete.confirm_placeholder": "Nom de l'environnement",
            "status.starting": "Démarrage",
            "status.stopping": "Fermeture",
            "status.running": "En cours",
            "status.stopped": "Arrêté",
            "error.start_failed": "Échec du démarrage",
            "error.delete_failed": "Échec de la suppression",
            "error.profile_message": "%@\n%@",
            "config_save.title": "Échec de l'enregistrement",
            "config_load.title": "Fichier de configuration corrompu",
            "config_load.message": "Le fichier de configuration n'a pas pu être lu. Une configuration par défaut propre a été chargée.",
            "config_load.message_with_backup": "Le fichier de configuration n'a pas pu être lu. La copie corrompue a été enregistrée ici :\n%@",
            "meta.port": "Port %d",
            "details.folder": "Dossier",
            "details.profile_path": "Chemin des données",
            "details.run_mode": "Mode d'exécution",
            "details.port": "Port de débogage",
            "details.cpu": "Coeurs CPU",
            "details.memory": "Mémoire",
            "date.today": "Aujourd'hui",
            "date.yesterday": "Hier",
            "date.days_ago": "il y a %d jours",
            "date.month_day": "%d/%d",
            "rename.title": "Renommer",
            "rename.hint": "Ajoutez un nom pour mieux l'identifier",
            "rename.placeholder": "Nom de cet environnement",
            "context.note": "Note",
            "note.hint": "Texte brut uniquement, jusqu'à 120 caractères Unicode",
            "note.placeholder": "Saisissez une note",
            "menu.open_panel": "Ouvrir le panneau",
            "menu.check_updates": "Rechercher des mises à jour",
            "menu.close_all_quit": "Tout fermer et quitter",
            "menu.quit": "Quitter",
            "settings.title": "Réglages",
            "settings.browser": "Navigateur",
            "settings.chrome_status": "État de Chrome",
            "settings.ready": "Prêt",
            "settings.not_installed": "Non installé",
            "settings.chrome_version": "Version de Chrome",
            "settings.unknown": "Inconnu",
            "settings.open_chrome_folder": "Ouvrir le dossier Chrome",
            "settings.redownload_chrome": "Retélécharger Chrome",
            "settings.data": "Données",
            "settings.data_path": "Dossier de données",
            "settings.open_data_folder": "Ouvrir le dossier de données",
            "settings.open_profiles_folder": "Ouvrir le dossier des profils",
            "settings.copy_path": "Copier le chemin",
            "settings.preferences": "Préférences",
            "settings.show_advanced": "Afficher les détails avancés",
            "settings.external_links": "Liens externes",
            "settings.open_to": "Ouvrir dans",
            "settings.set_default_browser": "Définir le navigateur par défaut",
            "settings.fingerprint_mode": "Mode variation",
            "settings.fingerprint_profiles": "Environnements",
            "settings.fingerprint_hint": "Désactivé utilise le mode de base ; activé passe en mode variation au prochain lancement avec port de debug et injection navigator",
            "settings.fingerprint_locked": "Fermez cet environnement avant de changer le mode",
            "settings.basic_mode": "Mode de base",
            "settings.variation_mode": "Mode variation",
            "settings.about_support": "À propos et aide",
            "settings.version_group": "Version et mises à jour",
            "settings.author_group": "Auteur",
            "settings.feedback_group": "Retour",
            "settings.app_version": "Version actuelle",
            "settings.view_releases": "Ouvrir la page des releases",
            "settings.author": "Auteur",
            "settings.email": "E-mail",
            "settings.open_issues": "Ouvrir les issues",
            "settings.copy_email": "Copier l'e-mail",
            "external_link.title": "Lien indisponible pour le moment",
            "external_link.message": "L'environnement du navigateur n'est pas encore prêt. Réessayez plus tard ou copiez ce lien :\n%@",
            "external_link.no_profile_message": "Aucun environnement n'est encore disponible. Créez ou choisissez-en un d'abord, puis réessayez ce lien :\n%@",
            "external_link.copy": "Copier le lien",
            "inspector.empty_title": "Sélectionnez un environnement",
            "inspector.empty_subtitle": "Les détails s'afficheront ici",
            "inspector.basic": "Informations de base",
            "inspector.advanced": "Informations avancées",
            "inspector.actions": "Actions",
            "inspector.error": "Erreur",
            "inspector.retry": "Réessayer",
            "inspector.clear_error": "Effacer",
            "inspector.open_profile_folder": "Ouvrir ce dossier de profil",
            "inspector.copy_profile_path": "Copier le chemin du profil",
            "inspector.last_used": "Dernière utilisation",
            "update.title": "Rechercher des mises à jour",
            "update.up_to_date": "Vous utilisez déjà la dernière version",
            "update.available_title": "Nouvelle version disponible",
            "update.available_message": "Dernière: %@\nActuelle: %@",
            "update.download": "Ouvrir les Releases",
            "update.failed": "Impossible de se connecter au serveur. Vérifiez le réseau.",
            "quit.title": "Confirmer la fermeture",
            "quit.confirm": "Fermer et quitter",
            "quit.message": "%d environnements sont encore en cours. Quitter les fermera tous.",
            "download.title": "Téléchargement du navigateur pour la première utilisation",
            "download.preparing": "Préparation...",
            "download.progress": "Téléchargement... (environ 237 Mo)",
            "download.installing": "Installation...",
            "download.verifying": "Vérification...",
            "download.failed": "Échec du téléchargement",
            "download.manual_title": "Vous pouvez aussi installer le navigateur manuellement :",
            "download.manual_steps": "1. Téléchargez Chrome : https://www.google.com/chrome/\n2. Ouvrez le DMG et déplacez « Google Chrome.app »\n   dans le dossier cible ci-dessous",
            "download.open_folder": "Ouvrir le dossier cible",
            "download.copy_error": "Copier l'erreur",
            "download.use_existing": "Utiliser Chrome existant",
            "download.retry": "Réessayer"
        ],
        .ru: [
            "app.name": "Изолятор браузера",
            "common.cancel": "Отмена",
            "common.confirm": "OK",
            "common.delete": "Удалить",
            "common.close": "Закрыть",
            "common.start": "Запустить",
            "common.later": "Позже",
            "language": "Язык",
            "profile.default_name": "Среда %d",
            "profile.display_name": "Среда %d - %@",
            "empty.title": "Сред пока нет",
            "empty.subtitle": "Нажмите + на панели инструментов",
            "toolbar.add": "Добавить среду",
            "toolbar.stop_all": "Закрыть все",
            "context.rename": "Переименовать",
            "context.delete": "Удалить",
            "delete.title": "Подтвердите удаление",
            "delete.message": "Переместить данные «%@» в корзину.\nТекущий размер данных: %@\nВведите имя среды для подтверждения.",
            "delete.confirm_placeholder": "Введите имя среды",
            "status.starting": "Запуск",
            "status.stopping": "Закрытие",
            "status.running": "Работает",
            "status.stopped": "Остановлена",
            "error.start_failed": "Не удалось запустить",
            "error.delete_failed": "Не удалось удалить",
            "error.profile_message": "%@\n%@",
            "config_save.title": "Не удалось сохранить",
            "config_load.title": "Файл конфигурации повреждён",
            "config_load.message": "Не удалось прочитать файл конфигурации. Загружена чистая конфигурация по умолчанию.",
            "config_load.message_with_backup": "Не удалось прочитать файл конфигурации. Повреждённая копия сохранена здесь:\n%@",
            "meta.port": "Порт %d",
            "details.folder": "Папка",
            "details.profile_path": "Путь данных",
            "details.run_mode": "Режим запуска",
            "details.port": "Debug-порт",
            "details.cpu": "Ядра CPU",
            "details.memory": "Память",
            "date.today": "Сегодня",
            "date.yesterday": "Вчера",
            "date.days_ago": "%d дн. назад",
            "date.month_day": "%d.%d",
            "rename.title": "Переименовать",
            "rename.hint": "Добавьте имя для удобного распознавания",
            "rename.placeholder": "Имя этой среды",
            "context.note": "Заметка",
            "note.hint": "Только обычный текст, до 120 символов Unicode",
            "note.placeholder": "Введите заметку",
            "menu.open_panel": "Открыть панель",
            "menu.check_updates": "Проверить обновления",
            "menu.close_all_quit": "Закрыть все и выйти",
            "menu.quit": "Выйти",
            "settings.title": "Настройки",
            "settings.browser": "Браузер",
            "settings.chrome_status": "Состояние Chrome",
            "settings.ready": "Готов",
            "settings.not_installed": "Не установлен",
            "settings.chrome_version": "Версия Chrome",
            "settings.unknown": "Неизвестно",
            "settings.open_chrome_folder": "Открыть папку Chrome",
            "settings.redownload_chrome": "Скачать Chrome заново",
            "settings.data": "Данные",
            "settings.data_path": "Папка данных",
            "settings.open_data_folder": "Открыть папку данных",
            "settings.open_profiles_folder": "Открыть папку профилей",
            "settings.copy_path": "Скопировать путь",
            "settings.preferences": "Параметры",
            "settings.show_advanced": "Показывать расширенные детали",
            "settings.external_links": "Внешние ссылки",
            "settings.open_to": "Открывать в",
            "settings.set_default_browser": "Сделать браузером по умолчанию",
            "settings.fingerprint_mode": "Режим различий",
            "settings.fingerprint_profiles": "Окружения",
            "settings.fingerprint_hint": "Выкл. — базовый режим; вкл. — режим различий при следующем запуске с debug-портом и navigator-инъекцией",
            "settings.fingerprint_locked": "Закройте это окружение перед изменением режима",
            "settings.basic_mode": "Базовый режим",
            "settings.variation_mode": "Режим различий",
            "settings.about_support": "О программе и поддержка",
            "settings.version_group": "Версия и обновления",
            "settings.author_group": "Автор",
            "settings.feedback_group": "Обратная связь",
            "settings.app_version": "Текущая версия",
            "settings.view_releases": "Посмотреть релизы",
            "settings.author": "Автор",
            "settings.email": "Почта",
            "settings.open_issues": "Посмотреть issues",
            "settings.copy_email": "Скопировать e-mail",
            "external_link.title": "Ссылку пока нельзя открыть",
            "external_link.message": "Браузерная среда ещё не готова. Повторите позже или скопируйте эту ссылку:\n%@",
            "external_link.no_profile_message": "Пока нет доступной среды. Сначала создайте или выберите её, затем повторите эту ссылку:\n%@",
            "external_link.copy": "Скопировать ссылку",
            "inspector.empty_title": "Выберите среду",
            "inspector.empty_subtitle": "Подробности появятся здесь",
            "inspector.basic": "Основная информация",
            "inspector.advanced": "Расширенная информация",
            "inspector.actions": "Действия",
            "inspector.error": "Ошибка",
            "inspector.retry": "Повторить",
            "inspector.clear_error": "Очистить",
            "inspector.open_profile_folder": "Открыть папку этой среды",
            "inspector.copy_profile_path": "Скопировать путь среды",
            "inspector.last_used": "Последнее использование",
            "update.title": "Проверить обновления",
            "update.up_to_date": "У вас уже последняя версия",
            "update.available_title": "Доступна новая версия",
            "update.available_message": "Последняя: %@\nТекущая: %@",
            "update.download": "Открыть Releases",
            "update.failed": "Не удалось подключиться к серверу. Проверьте сеть.",
            "quit.title": "Подтвердите выход",
            "quit.confirm": "Закрыть и выйти",
            "quit.message": "Еще работает сред: %d. При выходе все они будут закрыты.",
            "download.title": "Загрузка браузера для первого запуска",
            "download.preparing": "Подготовка...",
            "download.progress": "Загрузка... (около 237 МБ)",
            "download.installing": "Установка...",
            "download.verifying": "Проверка...",
            "download.failed": "Ошибка загрузки",
            "download.manual_title": "Браузер также можно установить вручную:",
            "download.manual_steps": "1. Скачайте Chrome: https://www.google.com/chrome/\n2. Откройте DMG и переместите «Google Chrome.app»\n   в целевую папку ниже",
            "download.open_folder": "Открыть целевую папку",
            "download.copy_error": "Скопировать ошибку",
            "download.use_existing": "Использовать текущий Chrome",
            "download.retry": "Повторить загрузку"
        ]
    ]
}
